
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.MCT
{
    partial class NewAssessmentTreatmentView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.MCT.NewAssessmentTreatmentViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NewAssessmentTreatmentView));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.SaveToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.Section1TabPage = new System.Windows.Forms.TabPage();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.SubstanceTreatment = new System.Windows.Forms.TextBox();
            this.groupBox18 = new System.Windows.Forms.GroupBox();
            this.TimePicker = new System.Windows.Forms.DateTimePicker();
            this.label12 = new System.Windows.Forms.Label();
            this.TimeStamp = new System.Windows.Forms.DateTimePicker();
            this.label7 = new System.Windows.Forms.Label();
            this.CaseNumber = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.Clinician = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.Support = new System.Windows.Forms.TextBox();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.Legal = new System.Windows.Forms.TextBox();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.PsychMeds = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.PsychTreatment = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.PsychHistory = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.RiskAssessment = new System.Windows.Forms.TextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.Problem = new System.Windows.Forms.TextBox();
            this.Section2TabPage = new System.Windows.Forms.TabPage();
            this.groupBox13 = new System.Windows.Forms.GroupBox();
            this.DiagnosticClient = new System.Windows.Forms.TextBox();
            this.groupBox14 = new System.Windows.Forms.GroupBox();
            this.DiagnosticImpression = new System.Windows.Forms.TextBox();
            this.groupBox11 = new System.Windows.Forms.GroupBox();
            this.Strengths = new System.Windows.Forms.TextBox();
            this.groupBox12 = new System.Windows.Forms.GroupBox();
            this.Mental = new System.Windows.Forms.TextBox();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.Somatic = new System.Windows.Forms.TextBox();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.Medical = new System.Windows.Forms.TextBox();
            this.Section3TabPage = new System.Windows.Forms.TabPage();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.Comments = new System.Windows.Forms.TextBox();
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.Treatment = new System.Windows.Forms.TextBox();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.CrisisPlan = new System.Windows.Forms.TextBox();
            this.Five = new System.Windows.Forms.GroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.Axis5 = new System.Windows.Forms.TextBox();
            this.Axis4 = new System.Windows.Forms.TextBox();
            this.Axis3 = new System.Windows.Forms.TextBox();
            this.Axis2 = new System.Windows.Forms.TextBox();
            this.Axis1 = new System.Windows.Forms.TextBox();
            this.textBox9 = new System.Windows.Forms.TextBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.textBox8 = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.Date = new System.Windows.Forms.TextBox();
            this.ClientDOBlbl = new System.Windows.Forms.Label();
            this.ClientFName = new System.Windows.Forms.Label();
            this.textBox10 = new System.Windows.Forms.TextBox();
            this.textBox13 = new System.Windows.Forms.TextBox();
            this.toolStrip1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.Section1TabPage.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox18.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.Section2TabPage.SuspendLayout();
            this.groupBox13.SuspendLayout();
            this.groupBox14.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.groupBox12.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.Section3TabPage.SuspendLayout();
            this.groupBox19.SuspendLayout();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            this.Five.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.SaveToolStripButton});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(630, 25);
            this.toolStrip1.TabIndex = 0;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // SaveToolStripButton
            // 
            this.SaveToolStripButton.Image = ((System.Drawing.Image)(resources.GetObject("SaveToolStripButton.Image")));
            this.SaveToolStripButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.SaveToolStripButton.Name = "SaveToolStripButton";
            this.SaveToolStripButton.Size = new System.Drawing.Size(51, 22);
            this.SaveToolStripButton.Text = "Save";
            this.SaveToolStripButton.Click += new System.EventHandler(this.SaveToolStripButton_Click);
            // 
            // tabControl1
            // 
            this.tabControl1.Appearance = System.Windows.Forms.TabAppearance.FlatButtons;
            this.tabControl1.Controls.Add(this.Section1TabPage);
            this.tabControl1.Controls.Add(this.Section2TabPage);
            this.tabControl1.Controls.Add(this.Section3TabPage);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 25);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(630, 677);
            this.tabControl1.TabIndex = 1;
            // 
            // Section1TabPage
            // 
            this.Section1TabPage.Controls.Add(this.groupBox6);
            this.Section1TabPage.Controls.Add(this.groupBox18);
            this.Section1TabPage.Controls.Add(this.groupBox5);
            this.Section1TabPage.Controls.Add(this.groupBox8);
            this.Section1TabPage.Controls.Add(this.groupBox7);
            this.Section1TabPage.Controls.Add(this.groupBox4);
            this.Section1TabPage.Controls.Add(this.groupBox3);
            this.Section1TabPage.Controls.Add(this.groupBox1);
            this.Section1TabPage.Controls.Add(this.groupBox2);
            this.Section1TabPage.Location = new System.Drawing.Point(4, 25);
            this.Section1TabPage.Name = "Section1TabPage";
            this.Section1TabPage.Padding = new System.Windows.Forms.Padding(3);
            this.Section1TabPage.Size = new System.Drawing.Size(622, 648);
            this.Section1TabPage.TabIndex = 0;
            this.Section1TabPage.Text = "Section 1";
            this.Section1TabPage.UseVisualStyleBackColor = true;
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.SubstanceTreatment);
            this.groupBox6.Location = new System.Drawing.Point(316, 422);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(300, 98);
            this.groupBox6.TabIndex = 11;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Substance/Etoh/Abuse Treatment";
            // 
            // SubstanceTreatment
            // 
            this.SubstanceTreatment.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SubstanceTreatment.Location = new System.Drawing.Point(3, 16);
            this.SubstanceTreatment.Multiline = true;
            this.SubstanceTreatment.Name = "SubstanceTreatment";
            this.SubstanceTreatment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.SubstanceTreatment.Size = new System.Drawing.Size(294, 79);
            this.SubstanceTreatment.TabIndex = 17;
            // 
            // groupBox18
            // 
            this.groupBox18.Controls.Add(this.TimePicker);
            this.groupBox18.Controls.Add(this.label12);
            this.groupBox18.Controls.Add(this.TimeStamp);
            this.groupBox18.Controls.Add(this.label7);
            this.groupBox18.Controls.Add(this.CaseNumber);
            this.groupBox18.Controls.Add(this.label8);
            this.groupBox18.Controls.Add(this.label9);
            this.groupBox18.Controls.Add(this.Clinician);
            this.groupBox18.Controls.Add(this.label10);
            this.groupBox18.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox18.Location = new System.Drawing.Point(3, 3);
            this.groupBox18.Name = "groupBox18";
            this.groupBox18.Size = new System.Drawing.Size(616, 103);
            this.groupBox18.TabIndex = 10;
            this.groupBox18.TabStop = false;
            this.groupBox18.Text = "Administrative";
            // 
            // TimePicker
            // 
            this.TimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.TimePicker.Location = new System.Drawing.Point(486, 70);
            this.TimePicker.Name = "TimePicker";
            this.TimePicker.ShowUpDown = true;
            this.TimePicker.Size = new System.Drawing.Size(89, 20);
            this.TimePicker.TabIndex = 44;
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(448, 70);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(33, 13);
            this.label12.TabIndex = 43;
            this.label12.Text = "Time:";
            // 
            // TimeStamp
            // 
            this.TimeStamp.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.TimeStamp.Location = new System.Drawing.Point(486, 44);
            this.TimeStamp.Name = "TimeStamp";
            this.TimeStamp.Size = new System.Drawing.Size(89, 20);
            this.TimeStamp.TabIndex = 4;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(17, 48);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(108, 13);
            this.label7.TabIndex = 42;
            this.label7.Text = "Additional Comments:";
            // 
            // CaseNumber
            // 
            this.CaseNumber.Location = new System.Drawing.Point(488, 17);
            this.CaseNumber.MaxLength = 7;
            this.CaseNumber.Name = "CaseNumber";
            this.CaseNumber.Size = new System.Drawing.Size(87, 20);
            this.CaseNumber.TabIndex = 2;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(448, 44);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(33, 13);
            this.label8.TabIndex = 39;
            this.label8.Text = "Date:";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(409, 17);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(74, 13);
            this.label9.TabIndex = 30;
            this.label9.Text = "Case Number:";
            // 
            // Clinician
            // 
            this.Clinician.Location = new System.Drawing.Point(79, 17);
            this.Clinician.Name = "Clinician";
            this.Clinician.Size = new System.Drawing.Size(274, 20);
            this.Clinician.TabIndex = 1;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(23, 19);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(58, 13);
            this.label10.TabIndex = 11;
            this.label10.Text = "Username:";
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.Support);
            this.groupBox5.Location = new System.Drawing.Point(6, 422);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(310, 98);
            this.groupBox5.TabIndex = 6;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Family/Social Support";
            // 
            // Support
            // 
            this.Support.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Support.Location = new System.Drawing.Point(3, 16);
            this.Support.Multiline = true;
            this.Support.Name = "Support";
            this.Support.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Support.Size = new System.Drawing.Size(304, 79);
            this.Support.TabIndex = 11;
            // 
            // groupBox8
            // 
            this.groupBox8.Controls.Add(this.Legal);
            this.groupBox8.Location = new System.Drawing.Point(319, 526);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(297, 98);
            this.groupBox8.TabIndex = 9;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "Legal History";
            // 
            // Legal
            // 
            this.Legal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Legal.Location = new System.Drawing.Point(3, 16);
            this.Legal.Multiline = true;
            this.Legal.Name = "Legal";
            this.Legal.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Legal.Size = new System.Drawing.Size(291, 79);
            this.Legal.TabIndex = 12;
            // 
            // groupBox7
            // 
            this.groupBox7.Controls.Add(this.PsychMeds);
            this.groupBox7.Location = new System.Drawing.Point(313, 318);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(306, 98);
            this.groupBox7.TabIndex = 8;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Pysch Meds";
            // 
            // PsychMeds
            // 
            this.PsychMeds.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PsychMeds.Location = new System.Drawing.Point(3, 16);
            this.PsychMeds.Multiline = true;
            this.PsychMeds.Name = "PsychMeds";
            this.PsychMeds.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.PsychMeds.Size = new System.Drawing.Size(300, 79);
            this.PsychMeds.TabIndex = 10;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.PsychTreatment);
            this.groupBox4.Location = new System.Drawing.Point(1, 318);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(310, 98);
            this.groupBox4.TabIndex = 5;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Psych Treatment";
            // 
            // PsychTreatment
            // 
            this.PsychTreatment.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PsychTreatment.Location = new System.Drawing.Point(3, 16);
            this.PsychTreatment.Multiline = true;
            this.PsychTreatment.Name = "PsychTreatment";
            this.PsychTreatment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.PsychTreatment.Size = new System.Drawing.Size(304, 79);
            this.PsychTreatment.TabIndex = 9;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.PsychHistory);
            this.groupBox3.Location = new System.Drawing.Point(1, 215);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(621, 98);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Pysch History";
            // 
            // PsychHistory
            // 
            this.PsychHistory.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PsychHistory.Location = new System.Drawing.Point(3, 16);
            this.PsychHistory.Multiline = true;
            this.PsychHistory.Name = "PsychHistory";
            this.PsychHistory.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.PsychHistory.Size = new System.Drawing.Size(615, 79);
            this.PsychHistory.TabIndex = 7;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.RiskAssessment);
            this.groupBox1.Location = new System.Drawing.Point(313, 112);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(310, 98);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Risk Assessment";
            // 
            // RiskAssessment
            // 
            this.RiskAssessment.Dock = System.Windows.Forms.DockStyle.Fill;
            this.RiskAssessment.Location = new System.Drawing.Point(3, 16);
            this.RiskAssessment.Multiline = true;
            this.RiskAssessment.Name = "RiskAssessment";
            this.RiskAssessment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.RiskAssessment.Size = new System.Drawing.Size(304, 79);
            this.RiskAssessment.TabIndex = 6;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.Problem);
            this.groupBox2.Location = new System.Drawing.Point(1, 112);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(306, 98);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Presenting/Current Problem";
            // 
            // Problem
            // 
            this.Problem.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Problem.Location = new System.Drawing.Point(3, 16);
            this.Problem.Multiline = true;
            this.Problem.Name = "Problem";
            this.Problem.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Problem.Size = new System.Drawing.Size(300, 79);
            this.Problem.TabIndex = 5;
            // 
            // Section2TabPage
            // 
            this.Section2TabPage.Controls.Add(this.groupBox13);
            this.Section2TabPage.Controls.Add(this.groupBox14);
            this.Section2TabPage.Controls.Add(this.groupBox11);
            this.Section2TabPage.Controls.Add(this.groupBox12);
            this.Section2TabPage.Controls.Add(this.groupBox9);
            this.Section2TabPage.Controls.Add(this.groupBox10);
            this.Section2TabPage.Location = new System.Drawing.Point(4, 25);
            this.Section2TabPage.Name = "Section2TabPage";
            this.Section2TabPage.Padding = new System.Windows.Forms.Padding(3);
            this.Section2TabPage.Size = new System.Drawing.Size(622, 648);
            this.Section2TabPage.TabIndex = 1;
            this.Section2TabPage.Text = "Section 2";
            this.Section2TabPage.UseVisualStyleBackColor = true;
            // 
            // groupBox13
            // 
            this.groupBox13.Controls.Add(this.DiagnosticClient);
            this.groupBox13.Location = new System.Drawing.Point(312, 195);
            this.groupBox13.Name = "groupBox13";
            this.groupBox13.Size = new System.Drawing.Size(310, 98);
            this.groupBox13.TabIndex = 9;
            this.groupBox13.TabStop = false;
            this.groupBox13.Text = "Diagnosis Reported by Client";
            // 
            // DiagnosticClient
            // 
            this.DiagnosticClient.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DiagnosticClient.Location = new System.Drawing.Point(3, 16);
            this.DiagnosticClient.Multiline = true;
            this.DiagnosticClient.Name = "DiagnosticClient";
            this.DiagnosticClient.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.DiagnosticClient.Size = new System.Drawing.Size(304, 79);
            this.DiagnosticClient.TabIndex = 17;
            // 
            // groupBox14
            // 
            this.groupBox14.Controls.Add(this.DiagnosticImpression);
            this.groupBox14.Location = new System.Drawing.Point(0, 195);
            this.groupBox14.Name = "groupBox14";
            this.groupBox14.Size = new System.Drawing.Size(306, 98);
            this.groupBox14.TabIndex = 8;
            this.groupBox14.TabStop = false;
            this.groupBox14.Text = "Diagnostic Impressions";
            // 
            // DiagnosticImpression
            // 
            this.DiagnosticImpression.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DiagnosticImpression.Location = new System.Drawing.Point(3, 16);
            this.DiagnosticImpression.Multiline = true;
            this.DiagnosticImpression.Name = "DiagnosticImpression";
            this.DiagnosticImpression.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.DiagnosticImpression.Size = new System.Drawing.Size(300, 79);
            this.DiagnosticImpression.TabIndex = 17;
            // 
            // groupBox11
            // 
            this.groupBox11.Controls.Add(this.Strengths);
            this.groupBox11.Location = new System.Drawing.Point(312, 96);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new System.Drawing.Size(310, 98);
            this.groupBox11.TabIndex = 7;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Strengths/Resources";
            // 
            // Strengths
            // 
            this.Strengths.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Strengths.Location = new System.Drawing.Point(3, 16);
            this.Strengths.Multiline = true;
            this.Strengths.Name = "Strengths";
            this.Strengths.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Strengths.Size = new System.Drawing.Size(304, 79);
            this.Strengths.TabIndex = 17;
            // 
            // groupBox12
            // 
            this.groupBox12.Controls.Add(this.Mental);
            this.groupBox12.Location = new System.Drawing.Point(0, 96);
            this.groupBox12.Name = "groupBox12";
            this.groupBox12.Size = new System.Drawing.Size(306, 98);
            this.groupBox12.TabIndex = 6;
            this.groupBox12.TabStop = false;
            this.groupBox12.Text = "Mental Status Exam";
            // 
            // Mental
            // 
            this.Mental.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Mental.Location = new System.Drawing.Point(3, 16);
            this.Mental.Multiline = true;
            this.Mental.Name = "Mental";
            this.Mental.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Mental.Size = new System.Drawing.Size(300, 79);
            this.Mental.TabIndex = 17;
            // 
            // groupBox9
            // 
            this.groupBox9.Controls.Add(this.Somatic);
            this.groupBox9.Location = new System.Drawing.Point(312, 0);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(310, 98);
            this.groupBox9.TabIndex = 5;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Somatic Meds";
            // 
            // Somatic
            // 
            this.Somatic.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Somatic.Location = new System.Drawing.Point(3, 16);
            this.Somatic.Multiline = true;
            this.Somatic.Name = "Somatic";
            this.Somatic.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Somatic.Size = new System.Drawing.Size(304, 79);
            this.Somatic.TabIndex = 17;
            // 
            // groupBox10
            // 
            this.groupBox10.Controls.Add(this.Medical);
            this.groupBox10.Location = new System.Drawing.Point(0, 0);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(306, 98);
            this.groupBox10.TabIndex = 4;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "Medical History";
            // 
            // Medical
            // 
            this.Medical.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Medical.Location = new System.Drawing.Point(3, 16);
            this.Medical.Multiline = true;
            this.Medical.Name = "Medical";
            this.Medical.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Medical.Size = new System.Drawing.Size(300, 79);
            this.Medical.TabIndex = 17;
            // 
            // Section3TabPage
            // 
            this.Section3TabPage.Controls.Add(this.groupBox19);
            this.Section3TabPage.Controls.Add(this.groupBox16);
            this.Section3TabPage.Controls.Add(this.groupBox15);
            this.Section3TabPage.Controls.Add(this.Five);
            this.Section3TabPage.Location = new System.Drawing.Point(4, 25);
            this.Section3TabPage.Name = "Section3TabPage";
            this.Section3TabPage.Size = new System.Drawing.Size(622, 648);
            this.Section3TabPage.TabIndex = 2;
            this.Section3TabPage.Text = "Section 3";
            this.Section3TabPage.UseVisualStyleBackColor = true;
            // 
            // groupBox19
            // 
            this.groupBox19.Controls.Add(this.Comments);
            this.groupBox19.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox19.Location = new System.Drawing.Point(0, 300);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(622, 100);
            this.groupBox19.TabIndex = 4;
            this.groupBox19.TabStop = false;
            this.groupBox19.Text = "Additional Comments";
            // 
            // Comments
            // 
            this.Comments.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Comments.Location = new System.Drawing.Point(3, 16);
            this.Comments.MaxLength = 9999999;
            this.Comments.Multiline = true;
            this.Comments.Name = "Comments";
            this.Comments.Size = new System.Drawing.Size(616, 81);
            this.Comments.TabIndex = 4;
            // 
            // groupBox16
            // 
            this.groupBox16.Controls.Add(this.Treatment);
            this.groupBox16.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox16.Location = new System.Drawing.Point(0, 200);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(622, 100);
            this.groupBox16.TabIndex = 2;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Treatment Plan";
            // 
            // Treatment
            // 
            this.Treatment.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Treatment.Location = new System.Drawing.Point(3, 16);
            this.Treatment.Multiline = true;
            this.Treatment.Name = "Treatment";
            this.Treatment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Treatment.Size = new System.Drawing.Size(616, 81);
            this.Treatment.TabIndex = 3;
            // 
            // groupBox15
            // 
            this.groupBox15.Controls.Add(this.CrisisPlan);
            this.groupBox15.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox15.Location = new System.Drawing.Point(0, 100);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(622, 100);
            this.groupBox15.TabIndex = 1;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "Crisis Plan";
            // 
            // CrisisPlan
            // 
            this.CrisisPlan.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CrisisPlan.Location = new System.Drawing.Point(3, 16);
            this.CrisisPlan.Multiline = true;
            this.CrisisPlan.Name = "CrisisPlan";
            this.CrisisPlan.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.CrisisPlan.Size = new System.Drawing.Size(616, 81);
            this.CrisisPlan.TabIndex = 3;
            // 
            // Five
            // 
            this.Five.Controls.Add(this.label5);
            this.Five.Controls.Add(this.label4);
            this.Five.Controls.Add(this.label3);
            this.Five.Controls.Add(this.label2);
            this.Five.Controls.Add(this.label1);
            this.Five.Controls.Add(this.Axis5);
            this.Five.Controls.Add(this.Axis4);
            this.Five.Controls.Add(this.Axis3);
            this.Five.Controls.Add(this.Axis2);
            this.Five.Controls.Add(this.Axis1);
            this.Five.Dock = System.Windows.Forms.DockStyle.Top;
            this.Five.Location = new System.Drawing.Point(0, 0);
            this.Five.Name = "Five";
            this.Five.Size = new System.Drawing.Size(622, 100);
            this.Five.TabIndex = 0;
            this.Five.TabStop = false;
            this.Five.Text = "Five-Axis Diagnosis";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(307, 48);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(39, 13);
            this.label5.TabIndex = 9;
            this.label5.Text = "Axis V:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(304, 26);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(42, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "Axis IV:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(30, 74);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(41, 13);
            this.label3.TabIndex = 7;
            this.label3.Text = "Axis III:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(33, 52);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(38, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Axis II:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(36, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(35, 13);
            this.label1.TabIndex = 5;
            this.label1.Text = "Axis I:";
            // 
            // Axis5
            // 
            this.Axis5.Location = new System.Drawing.Point(348, 45);
            this.Axis5.Name = "Axis5";
            this.Axis5.Size = new System.Drawing.Size(191, 20);
            this.Axis5.TabIndex = 4;
            // 
            // Axis4
            // 
            this.Axis4.Location = new System.Drawing.Point(348, 19);
            this.Axis4.Name = "Axis4";
            this.Axis4.Size = new System.Drawing.Size(191, 20);
            this.Axis4.TabIndex = 3;
            // 
            // Axis3
            // 
            this.Axis3.Location = new System.Drawing.Point(77, 71);
            this.Axis3.Name = "Axis3";
            this.Axis3.Size = new System.Drawing.Size(191, 20);
            this.Axis3.TabIndex = 2;
            // 
            // Axis2
            // 
            this.Axis2.Location = new System.Drawing.Point(77, 45);
            this.Axis2.Name = "Axis2";
            this.Axis2.Size = new System.Drawing.Size(191, 20);
            this.Axis2.TabIndex = 1;
            // 
            // Axis1
            // 
            this.Axis1.Location = new System.Drawing.Point(77, 19);
            this.Axis1.Name = "Axis1";
            this.Axis1.Size = new System.Drawing.Size(191, 20);
            this.Axis1.TabIndex = 0;
            // 
            // textBox9
            // 
            this.textBox9.Location = new System.Drawing.Point(16, 64);
            this.textBox9.MaxLength = 5;
            this.textBox9.Multiline = true;
            this.textBox9.Name = "textBox9";
            this.textBox9.Size = new System.Drawing.Size(337, 98);
            this.textBox9.TabIndex = 41;
            // 
            // textBox1
            // 
            this.textBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox1.Location = new System.Drawing.Point(3, 16);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox1.Size = new System.Drawing.Size(300, 79);
            this.textBox1.TabIndex = 17;
            // 
            // textBox2
            // 
            this.textBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox2.Location = new System.Drawing.Point(3, 16);
            this.textBox2.Multiline = true;
            this.textBox2.Name = "textBox2";
            this.textBox2.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox2.Size = new System.Drawing.Size(300, 79);
            this.textBox2.TabIndex = 17;
            // 
            // textBox3
            // 
            this.textBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox3.Location = new System.Drawing.Point(3, 16);
            this.textBox3.Multiline = true;
            this.textBox3.Name = "textBox3";
            this.textBox3.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox3.Size = new System.Drawing.Size(300, 79);
            this.textBox3.TabIndex = 17;
            // 
            // textBox4
            // 
            this.textBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox4.Location = new System.Drawing.Point(3, 16);
            this.textBox4.Multiline = true;
            this.textBox4.Name = "textBox4";
            this.textBox4.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox4.Size = new System.Drawing.Size(304, 79);
            this.textBox4.TabIndex = 17;
            // 
            // textBox5
            // 
            this.textBox5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox5.Location = new System.Drawing.Point(3, 16);
            this.textBox5.Multiline = true;
            this.textBox5.Name = "textBox5";
            this.textBox5.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox5.Size = new System.Drawing.Size(304, 79);
            this.textBox5.TabIndex = 17;
            // 
            // textBox6
            // 
            this.textBox6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox6.Location = new System.Drawing.Point(3, 16);
            this.textBox6.Multiline = true;
            this.textBox6.Name = "textBox6";
            this.textBox6.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox6.Size = new System.Drawing.Size(304, 79);
            this.textBox6.TabIndex = 17;
            // 
            // textBox7
            // 
            this.textBox7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox7.Location = new System.Drawing.Point(3, 16);
            this.textBox7.Multiline = true;
            this.textBox7.Name = "textBox7";
            this.textBox7.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox7.Size = new System.Drawing.Size(304, 79);
            this.textBox7.TabIndex = 17;
            // 
            // textBox8
            // 
            this.textBox8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox8.Location = new System.Drawing.Point(3, 16);
            this.textBox8.Multiline = true;
            this.textBox8.Name = "textBox8";
            this.textBox8.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBox8.Size = new System.Drawing.Size(300, 79);
            this.textBox8.TabIndex = 17;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(17, 48);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(108, 13);
            this.label6.TabIndex = 42;
            this.label6.Text = "Additional Comments:";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(450, 44);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(33, 13);
            this.label11.TabIndex = 39;
            this.label11.Text = "Date:";
            // 
            // Date
            // 
            this.Date.Location = new System.Drawing.Point(496, 41);
            this.Date.MaxLength = 5;
            this.Date.Name = "Date";
            this.Date.Size = new System.Drawing.Size(100, 20);
            this.Date.TabIndex = 38;
            // 
            // ClientDOBlbl
            // 
            this.ClientDOBlbl.AutoSize = true;
            this.ClientDOBlbl.Location = new System.Drawing.Point(409, 17);
            this.ClientDOBlbl.Name = "ClientDOBlbl";
            this.ClientDOBlbl.Size = new System.Drawing.Size(74, 13);
            this.ClientDOBlbl.TabIndex = 30;
            this.ClientDOBlbl.Text = "Case Number:";
            // 
            // ClientFName
            // 
            this.ClientFName.AutoSize = true;
            this.ClientFName.Location = new System.Drawing.Point(23, 19);
            this.ClientFName.Name = "ClientFName";
            this.ClientFName.Size = new System.Drawing.Size(49, 13);
            this.ClientFName.TabIndex = 11;
            this.ClientFName.Text = "Clinician:";
            // 
            // textBox10
            // 
            this.textBox10.Location = new System.Drawing.Point(496, 17);
            this.textBox10.MaxLength = 5;
            this.textBox10.Name = "textBox10";
            this.textBox10.Size = new System.Drawing.Size(48, 20);
            this.textBox10.TabIndex = 40;
            // 
            // textBox13
            // 
            this.textBox13.Location = new System.Drawing.Point(79, 17);
            this.textBox13.Name = "textBox13";
            this.textBox13.Size = new System.Drawing.Size(274, 20);
            this.textBox13.TabIndex = 17;
            // 
            // NewAssessmentTreatmentView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.toolStrip1);
            this.Name = "NewAssessmentTreatmentView";
            this.Size = new System.Drawing.Size(630, 702);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.Section1TabPage.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox18.ResumeLayout(false);
            this.groupBox18.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.Section2TabPage.ResumeLayout(false);
            this.groupBox13.ResumeLayout(false);
            this.groupBox13.PerformLayout();
            this.groupBox14.ResumeLayout(false);
            this.groupBox14.PerformLayout();
            this.groupBox11.ResumeLayout(false);
            this.groupBox11.PerformLayout();
            this.groupBox12.ResumeLayout(false);
            this.groupBox12.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.Section3TabPage.ResumeLayout(false);
            this.groupBox19.ResumeLayout(false);
            this.groupBox19.PerformLayout();
            this.groupBox16.ResumeLayout(false);
            this.groupBox16.PerformLayout();
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            this.Five.ResumeLayout(false);
            this.Five.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton SaveToolStripButton;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage Section1TabPage;
        private System.Windows.Forms.TabPage Section2TabPage;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.TextBox PsychHistory;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TextBox RiskAssessment;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TextBox Problem;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.TextBox Legal;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.TextBox PsychMeds;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TextBox Support;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.TextBox PsychTreatment;
        private System.Windows.Forms.TabPage Section3TabPage;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.TextBox Somatic;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.TextBox Medical;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.GroupBox groupBox13;
        private System.Windows.Forms.TextBox DiagnosticClient;
        private System.Windows.Forms.GroupBox groupBox14;
        private System.Windows.Forms.TextBox DiagnosticImpression;
        private System.Windows.Forms.GroupBox groupBox11;
        private System.Windows.Forms.TextBox Strengths;
        private System.Windows.Forms.GroupBox groupBox12;
        private System.Windows.Forms.TextBox Mental;
        private System.Windows.Forms.GroupBox Five;
        private System.Windows.Forms.TextBox Axis5;
        private System.Windows.Forms.TextBox Axis4;
        private System.Windows.Forms.TextBox Axis3;
        private System.Windows.Forms.TextBox Axis2;
        private System.Windows.Forms.TextBox Axis1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox groupBox16;
        private System.Windows.Forms.TextBox Treatment;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.TextBox CrisisPlan;
        private System.Windows.Forms.GroupBox groupBox18;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox textBox9;
        private System.Windows.Forms.TextBox textBox10;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox textBox13;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox CaseNumber;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.TextBox Date;
        private System.Windows.Forms.Label ClientDOBlbl;
        private System.Windows.Forms.TextBox Clinician;
        private System.Windows.Forms.Label ClientFName;
        private System.Windows.Forms.DateTimePicker TimeStamp;
        private System.Windows.Forms.GroupBox groupBox19;
        private System.Windows.Forms.TextBox Comments;
        private System.Windows.Forms.DateTimePicker TimePicker;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.TextBox SubstanceTreatment;
    }
}

