
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.MCT
{
    partial class MCTView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.MCT.MCTViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.FormSelectionGroupBox = new System.Windows.Forms.GroupBox();
            this.IntakeButton = new System.Windows.Forms.Button();
            this.LethalityButton = new System.Windows.Forms.Button();
            this.MCTDispatchButton = new System.Windows.Forms.Button();
            this.AssesTreatmentButton = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.FormSelectionGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // FormSelectionGroupBox
            // 
            this.FormSelectionGroupBox.Controls.Add(this.button1);
            this.FormSelectionGroupBox.Controls.Add(this.IntakeButton);
            this.FormSelectionGroupBox.Controls.Add(this.LethalityButton);
            this.FormSelectionGroupBox.Controls.Add(this.MCTDispatchButton);
            this.FormSelectionGroupBox.Controls.Add(this.AssesTreatmentButton);
            this.FormSelectionGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.FormSelectionGroupBox.Location = new System.Drawing.Point(0, 0);
            this.FormSelectionGroupBox.Name = "FormSelectionGroupBox";
            this.FormSelectionGroupBox.Size = new System.Drawing.Size(422, 278);
            this.FormSelectionGroupBox.TabIndex = 0;
            this.FormSelectionGroupBox.TabStop = false;
            this.FormSelectionGroupBox.Text = "Forms Menu";
            // 
            // IntakeButton
            // 
            this.IntakeButton.Location = new System.Drawing.Point(216, 122);
            this.IntakeButton.Name = "IntakeButton";
            this.IntakeButton.Size = new System.Drawing.Size(200, 50);
            this.IntakeButton.TabIndex = 6;
            this.IntakeButton.Text = "Intake";
            this.IntakeButton.UseVisualStyleBackColor = true;
            this.IntakeButton.Click += new System.EventHandler(this.IntakeButton_Click);
            // 
            // LethalityButton
            // 
            this.LethalityButton.Location = new System.Drawing.Point(111, 178);
            this.LethalityButton.Name = "LethalityButton";
            this.LethalityButton.Size = new System.Drawing.Size(200, 50);
            this.LethalityButton.TabIndex = 3;
            this.LethalityButton.Text = "Lethality Sheet";
            this.LethalityButton.UseVisualStyleBackColor = true;
            this.LethalityButton.Click += new System.EventHandler(this.LethalityButton_Click);
            // 
            // MCTDispatchButton
            // 
            this.MCTDispatchButton.Location = new System.Drawing.Point(111, 78);
            this.MCTDispatchButton.Name = "MCTDispatchButton";
            this.MCTDispatchButton.Size = new System.Drawing.Size(200, 50);
            this.MCTDispatchButton.TabIndex = 1;
            this.MCTDispatchButton.Text = "MCT Dispatch";
            this.MCTDispatchButton.UseVisualStyleBackColor = true;
            this.MCTDispatchButton.Click += new System.EventHandler(this.MCTDispatchButton_Click);
            // 
            // AssesTreatmentButton
            // 
            this.AssesTreatmentButton.Location = new System.Drawing.Point(111, 28);
            this.AssesTreatmentButton.Name = "AssesTreatmentButton";
            this.AssesTreatmentButton.Size = new System.Drawing.Size(200, 50);
            this.AssesTreatmentButton.TabIndex = 0;
            this.AssesTreatmentButton.Text = "Assessment and Treatment";
            this.AssesTreatmentButton.UseVisualStyleBackColor = true;
            this.AssesTreatmentButton.Click += new System.EventHandler(this.AssesTreatmentButton_Click);
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(111, 234);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(200, 50);
            this.button1.TabIndex = 7;
            this.button1.Text = "Consent For Services";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // MCTView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.FormSelectionGroupBox);
            this.Name = "MCTView";
            this.Size = new System.Drawing.Size(422, 278);
            this.Load += new System.EventHandler(this.MCTView_Load);
            this.FormSelectionGroupBox.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox FormSelectionGroupBox;
        private System.Windows.Forms.Button AssesTreatmentButton;
        private System.Windows.Forms.Button MCTDispatchButton;
        private System.Windows.Forms.Button LethalityButton;
        private System.Windows.Forms.Button IntakeButton;
        private System.Windows.Forms.Button button1;
    }
}

