//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// This class contains placeholder methods for the common module initialization 
// tasks, such as adding services, or user-interface element
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.Commands;
using Sante.EMR.SmartClient.OPS.Constants;
using Sante.EMR.SmartClient.OPS.Properties;
using Microsoft.Practices.CompositeUI.EventBroker;

namespace Sante.EMR.SmartClient.OPS
{
    public class ModuleController : WorkItemController
    {
        public override void Run()
        {
            AddServices();
            ExtendMenu();
            ExtendToolStrip();
            AddViews();
            AddCommands();
        }

        private void AddServices()
        {
            //TODO: add services provided by the Module. See: Add or AddNew method in 
            //		WorkItem.Services collection or see ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.2005Nov.cab/CAB/html/03-020-Adding%20Services.htm
        }

        private void ExtendMenu()
        {
            //TODO: add menu items here, normally by calling the "Add" method on
            //		on the WorkItem.UIExtensionSites collection. For an example 
            //		See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-04-340-Showing_UIElements.htm
            ToolStripMenuItem menu = new ToolStripMenuItem(Properties.Resources.ModuleTitle);


            //WorkItem.Commands[CommandNames.New].AddInvoker(item, "Click");

            WorkItem.UIExtensionSites[UIExtensionSiteNames.NewMenu].Add(menu);
        }

        /// <summary>
        /// 
        /// </summary>
        private void ExtendToolStrip()
        {

            this.RegisterLaunchPoint(Properties.Resources.ModuleTitle, Properties.Resources.OPSIcon, CommandNames.OPSMenu);
        }

        private void AddViews()
        {
            //TODO: create the Module views, add them to the WorkItem and show them in 
            //		a Workspace. See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-040-How_to_Add_a_View_with_a_Presenter.htm

            // To create and add a view you can customize the following sentence
            //NewIntakeFormView view = this.ShowViewInWorkspace<NewIntakeFormView>(WorkspaceNames.ModalWindows);
            ShowViewInWorkspace<OPSView>(WorkspaceNames.PrimaryWorkspace);
             
        }

        private void AddCommands()
        {
            //WorkItem.Commands[CommandNames.ShowNewIntakeForm].AddInvoker(button, "Click");
            
        }

        [CommandHandler(CommandNames.OPSMenu)]
        public void OnOPSMenu(object sender, EventArgs e)
        {
            ShowViewInWorkspace<OPSView>(WorkspaceNames.PrimaryWorkspace);
        }

        [EventSubscription(EventTopicNames.OnStartUp, ThreadOption.UserInterface)]
        public void OnStartup(object sender, EventArgs e)
        {
            OnOPSMenu(sender, e);
        }
         
        [EventSubscription(EventTopicNames.ShowIntakeForm, ThreadOption.UserInterface)]
        public void OnShowNewIntakeForm(object sender, EventArgs e)
        {
            NewIntakeFormView view = ShowViewInWorkspace<NewIntakeFormView>(WorkspaceNames.ModalWindows);            
        }

        [EventSubscription(EventTopicNames.ShowIntakeFormPG, ThreadOption.UserInterface)]
        public void OnShowNewIntakeFormPG(object sender, EventArgs e)
        {
            NewIntakePGFormView view = ShowViewInWorkspace<NewIntakePGFormView>(WorkspaceNames.ModalWindows);
        }

        [EventSubscription(EventTopicNames.ShowIntakeFormES, ThreadOption.UserInterface)]
        public void OnShowNewIntakeFormES(object sender, EventArgs e)
        {
            NewIntakeESFormView view = ShowViewInWorkspace<NewIntakeESFormView>(WorkspaceNames.ModalWindows);
        }

        [EventSubscription(EventTopicNames.ShowNewLethalityForm, ThreadOption.UserInterface)]
        public void OnShowNewLethalityForm(object sender, EventArgs e)
        {
            ShowViewInWorkspace<NewLethalityFormView>(WorkspaceNames.ModalWindows);
        }

        [EventSubscription(EventTopicNames.ShowOPSTelephoneContact, ThreadOption.UserInterface)]
        public void OnShowCaseNumberForm(object sender, EventArgs eventArgs)
        {//TODO: Add your code here
            ShowViewInWorkspace<TelephoneContactView>(WorkspaceNames.ModalWindows);
        }
        

        //TODO: Add CommandHandlers and/or Event Subscriptions
        //		See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-04-350-Registering_Commands.htm
        //		See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-04-320-Publishing_and_Subscribing_to_Events.htm
    }
}
