//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using BusinessEntitiesAlias = Sante.EMR.SmartClient.Infrastructure.Interface.BusinessEntities;
using Microsoft.Practices.CompositeUI.EventBroker;
using System.Windows.Forms;
using Sante.EMR.SmartClient.Infrastructure.Interface.Constants;
using Sante.EMR.SmartClient.Module.Services;
using Sante.EMR.SmartClient.Infrastructure.Interface.BusinessEntities;
using System.Collections.Generic;

namespace Sante.EMR.SmartClient.OPS
{
    public partial class NewLethalityFormViewPresenter : Presenter<INewLethalityFormView>
    {
        IOutboxService _outbox;
        public NewLethalityFormViewPresenter([ServiceDependency] IOutboxService outbox)
        {
            _outbox = outbox;
        }

        /// <summary>
        /// This method is a placeholder that will be called by the view when it has been loaded.
        /// </summary>
        public override void OnViewReady()
        {
            base.OnViewReady();
        }

        /// <summary>
        /// Close the view
        /// </summary>
        public void OnCloseView()
        {
            base.CloseView();
        }

        internal void SaveForm(Sante.EMR.SmartClient.Infrastructure.Interface.BusinessEntities.Form _form)
        {
            EventArgs<BusinessEntitiesAlias.Form> e = new EventArgs<BusinessEntitiesAlias.Form>(_form);

            try
            {
                WorkItem.EventTopics[EventTopicNames.SaveFormEvent].Fire(this, e, WorkItem, PublicationScope.Global);

               
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
            }

        }

        internal void ShowMsg(string p)
        {
            MessageBox.Show(p);
        }
    }
}

