//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// This class is the concrete implementation of a View in the Model-View-Presenter 
// pattern. Communication between the Presenter and this class is acheived through 
// an interface to facilitate separation and testability.
// Note that the Presenter generated by the same recipe, will automatically be created
// by CAB through [CreateNew] and bidirectional references will be added.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using Microsoft.Practices.CompositeUI.SmartParts;
using Microsoft.Practices.ObjectBuilder;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI.Commands;
using Sante.EMR.SmartClient.Infrastructure.Interface.Constants;

namespace Sante.EMR.SmartClient.OutBox
{
    public partial class OutBoxView : UserControl, IOutBoxView, ISmartPartInfoProvider
    {
        
        public OutBoxView()
        {
            InitializeComponent();
        }

        protected override void OnLoad(EventArgs e)
        {
            _presenter.OnViewReady();
            base.OnLoad(e);

        }

        public ISmartPartInfo GetSmartPartInfo(Type smartPartInfoType)
        {
            return _presenter.GetSmartPartInfo(smartPartInfoType);// throw new Exception("The method or operation is not implemented.");
        }


        #region IOutBoxView Members

        public void ShowOfflineMessage()
        {
            //throw new Exception("The method or operation is not implemented.");
        }

        public void ShowConnectionError()
        {
            //throw new Exception("The method or operation is not implemented.");
        }

        #endregion

        #region IOutBoxView Members

        public void UpdateOutbox(Sante.EMR.SmartClient.Infrastructure.Interface.BusinessEntities.Form form)
        {
            this.formBindingSource.Add(form);
        }

        #endregion
    }
}

