
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.OPS
{
    partial class NewLethalityFormView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.OPS.NewLethalityFormViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NewLethalityFormView));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.SaveToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.Employee = new System.Windows.Forms.TextBox();
            this.Employeelbl = new System.Windows.Forms.Label();
            this.CaseNumber = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.Time = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.Date = new System.Windows.Forms.TextBox();
            this.ClientDOBlbl = new System.Windows.Forms.Label();
            this.PfirstName = new System.Windows.Forms.TextBox();
            this.PlastName = new System.Windows.Forms.TextBox();
            this.ClientLName = new System.Windows.Forms.Label();
            this.ClientFName = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox19 = new System.Windows.Forms.GroupBox();
            this.MostSerious_1 = new System.Windows.Forms.RadioButton();
            this.MostSerious_0 = new System.Windows.Forms.RadioButton();
            this.MostSerious_2 = new System.Windows.Forms.RadioButton();
            this.MostSerious_3 = new System.Windows.Forms.RadioButton();
            this.groupBox18 = new System.Windows.Forms.GroupBox();
            this.MostLethal_1 = new System.Windows.Forms.RadioButton();
            this.MostLethal_0 = new System.Windows.Forms.RadioButton();
            this.MostLethal_2 = new System.Windows.Forms.RadioButton();
            this.MostLethal_3 = new System.Windows.Forms.RadioButton();
            this.groupBox17 = new System.Windows.Forms.GroupBox();
            this.MostRecent_1 = new System.Windows.Forms.RadioButton();
            this.MostRecent_0 = new System.Windows.Forms.RadioButton();
            this.MostRecent_2 = new System.Windows.Forms.RadioButton();
            this.MostRecent_3 = new System.Windows.Forms.RadioButton();
            this.groupBox11 = new System.Windows.Forms.GroupBox();
            this.Supports_0 = new System.Windows.Forms.RadioButton();
            this.Supports_2 = new System.Windows.Forms.RadioButton();
            this.Supports_1 = new System.Windows.Forms.RadioButton();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.DepressionSymptoms_0 = new System.Windows.Forms.RadioButton();
            this.DepressionSymptoms_1 = new System.Windows.Forms.RadioButton();
            this.DepressionSymptoms_2 = new System.Windows.Forms.RadioButton();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.PriorAttempts_0 = new System.Windows.Forms.RadioButton();
            this.PriorAttempts_1 = new System.Windows.Forms.RadioButton();
            this.PriorAttempts_2 = new System.Windows.Forms.RadioButton();
            this.groupBox16 = new System.Windows.Forms.GroupBox();
            this.Alternatives_0 = new System.Windows.Forms.RadioButton();
            this.Alternatives_1 = new System.Windows.Forms.RadioButton();
            this.Alternatives_2 = new System.Windows.Forms.RadioButton();
            this.groupBox15 = new System.Windows.Forms.GroupBox();
            this.Consequences_0 = new System.Windows.Forms.RadioButton();
            this.Consequences_1 = new System.Windows.Forms.RadioButton();
            this.Consequences_2 = new System.Windows.Forms.RadioButton();
            this.groupBox14 = new System.Windows.Forms.GroupBox();
            this.FeelsJustified_0 = new System.Windows.Forms.RadioButton();
            this.FeelsJustified_1 = new System.Windows.Forms.RadioButton();
            this.FeelsJustified_2 = new System.Windows.Forms.RadioButton();
            this.groupBox13 = new System.Windows.Forms.GroupBox();
            this.CallerAlone_0 = new System.Windows.Forms.RadioButton();
            this.CallerAlone_1 = new System.Windows.Forms.RadioButton();
            this.CallerAlone_2 = new System.Windows.Forms.RadioButton();
            this.groupBox12 = new System.Windows.Forms.GroupBox();
            this.Comments = new System.Windows.Forms.TextBox();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.Total2 = new System.Windows.Forms.TextBox();
            this.Total1 = new System.Windows.Forms.TextBox();
            this.Score = new System.Windows.Forms.TextBox();
            this.Total3 = new System.Windows.Forms.TextBox();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.FamilyAttemptsCompletions_3 = new System.Windows.Forms.RadioButton();
            this.FamilyAttemptsCompletions_0 = new System.Windows.Forms.RadioButton();
            this.FamilyAttemptsCompletions_1 = new System.Windows.Forms.RadioButton();
            this.FamilyAttemptsCompletions_2 = new System.Windows.Forms.RadioButton();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.DrugAlcoholUse_10 = new System.Windows.Forms.RadioButton();
            this.DrugAlcoholUse_0 = new System.Windows.Forms.RadioButton();
            this.DrugAlcoholUse_1 = new System.Windows.Forms.RadioButton();
            this.DrugAlcoholUse_2 = new System.Windows.Forms.RadioButton();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.Ability_0 = new System.Windows.Forms.RadioButton();
            this.Ability_1 = new System.Windows.Forms.RadioButton();
            this.Ability_2 = new System.Windows.Forms.RadioButton();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.Accessibility_0 = new System.Windows.Forms.RadioButton();
            this.Accessibility_1 = new System.Windows.Forms.RadioButton();
            this.Accessibility_2 = new System.Windows.Forms.RadioButton();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.Method_10 = new System.Windows.Forms.RadioButton();
            this.Method_0 = new System.Windows.Forms.RadioButton();
            this.Method_1 = new System.Windows.Forms.RadioButton();
            this.Method_2 = new System.Windows.Forms.RadioButton();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.PlanSelect_0 = new System.Windows.Forms.RadioButton();
            this.PlanSelect_1 = new System.Windows.Forms.RadioButton();
            this.PlanSelect_2 = new System.Windows.Forms.RadioButton();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.toolStrip1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox19.SuspendLayout();
            this.groupBox18.SuspendLayout();
            this.groupBox17.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox16.SuspendLayout();
            this.groupBox15.SuspendLayout();
            this.groupBox14.SuspendLayout();
            this.groupBox13.SuspendLayout();
            this.groupBox12.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.SaveToolStripButton});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(948, 25);
            this.toolStrip1.TabIndex = 1;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // SaveToolStripButton
            // 
            this.SaveToolStripButton.Image = ((System.Drawing.Image)(resources.GetObject("SaveToolStripButton.Image")));
            this.SaveToolStripButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.SaveToolStripButton.Name = "SaveToolStripButton";
            this.SaveToolStripButton.Size = new System.Drawing.Size(51, 22);
            this.SaveToolStripButton.Text = "Save";
            this.SaveToolStripButton.Click += new System.EventHandler(this.SaveToolStripButton_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.Employee);
            this.groupBox2.Controls.Add(this.Employeelbl);
            this.groupBox2.Controls.Add(this.CaseNumber);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.Time);
            this.groupBox2.Controls.Add(this.label11);
            this.groupBox2.Controls.Add(this.Date);
            this.groupBox2.Controls.Add(this.ClientDOBlbl);
            this.groupBox2.Controls.Add(this.PfirstName);
            this.groupBox2.Controls.Add(this.PlastName);
            this.groupBox2.Controls.Add(this.ClientLName);
            this.groupBox2.Controls.Add(this.ClientFName);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox2.Location = new System.Drawing.Point(0, 25);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(948, 48);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Administrative";
            // 
            // Employee
            // 
            this.Employee.Location = new System.Drawing.Point(859, 17);
            this.Employee.Name = "Employee";
            this.Employee.Size = new System.Drawing.Size(83, 20);
            this.Employee.TabIndex = 43;
            // 
            // Employeelbl
            // 
            this.Employeelbl.AutoSize = true;
            this.Employeelbl.Location = new System.Drawing.Point(799, 17);
            this.Employeelbl.Name = "Employeelbl";
            this.Employeelbl.Size = new System.Drawing.Size(56, 13);
            this.Employeelbl.TabIndex = 44;
            this.Employeelbl.Text = "Employee:";
            // 
            // CaseNumber
            // 
            this.CaseNumber.FormattingEnabled = true;
            this.CaseNumber.Location = new System.Drawing.Point(692, 17);
            this.CaseNumber.Name = "CaseNumber";
            this.CaseNumber.Size = new System.Drawing.Size(101, 21);
            this.CaseNumber.TabIndex = 2;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(513, 17);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(33, 13);
            this.label1.TabIndex = 42;
            this.label1.Text = "Time:";
            // 
            // Time
            // 
            this.Time.Location = new System.Drawing.Point(551, 17);
            this.Time.MaxLength = 5;
            this.Time.Name = "Time";
            this.Time.Size = new System.Drawing.Size(58, 20);
            this.Time.TabIndex = 5;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(391, 17);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(33, 13);
            this.label11.TabIndex = 39;
            this.label11.Text = "Date:";
            // 
            // Date
            // 
            this.Date.Location = new System.Drawing.Point(424, 17);
            this.Date.MaxLength = 5;
            this.Date.Name = "Date";
            this.Date.Size = new System.Drawing.Size(82, 20);
            this.Date.TabIndex = 4;
            // 
            // ClientDOBlbl
            // 
            this.ClientDOBlbl.AutoSize = true;
            this.ClientDOBlbl.Location = new System.Drawing.Point(612, 17);
            this.ClientDOBlbl.Name = "ClientDOBlbl";
            this.ClientDOBlbl.Size = new System.Drawing.Size(74, 13);
            this.ClientDOBlbl.TabIndex = 30;
            this.ClientDOBlbl.Text = "Case Number:";
            // 
            // PfirstName
            // 
            this.PfirstName.Location = new System.Drawing.Point(72, 17);
            this.PfirstName.Name = "PfirstName";
            this.PfirstName.Size = new System.Drawing.Size(124, 20);
            this.PfirstName.TabIndex = 1;
            // 
            // PlastName
            // 
            this.PlastName.Location = new System.Drawing.Point(265, 17);
            this.PlastName.Name = "PlastName";
            this.PlastName.Size = new System.Drawing.Size(122, 20);
            this.PlastName.TabIndex = 3;
            // 
            // ClientLName
            // 
            this.ClientLName.AutoSize = true;
            this.ClientLName.Location = new System.Drawing.Point(206, 17);
            this.ClientLName.Name = "ClientLName";
            this.ClientLName.Size = new System.Drawing.Size(61, 13);
            this.ClientLName.TabIndex = 12;
            this.ClientLName.Text = "Last Name:";
            // 
            // ClientFName
            // 
            this.ClientFName.AutoSize = true;
            this.ClientFName.Location = new System.Drawing.Point(6, 17);
            this.ClientFName.Name = "ClientFName";
            this.ClientFName.Size = new System.Drawing.Size(60, 13);
            this.ClientFName.TabIndex = 11;
            this.ClientFName.Text = "First Name:";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.groupBox19);
            this.groupBox1.Controls.Add(this.groupBox18);
            this.groupBox1.Controls.Add(this.groupBox17);
            this.groupBox1.Controls.Add(this.groupBox11);
            this.groupBox1.Controls.Add(this.groupBox10);
            this.groupBox1.Controls.Add(this.groupBox8);
            this.groupBox1.Controls.Add(this.groupBox16);
            this.groupBox1.Controls.Add(this.groupBox15);
            this.groupBox1.Controls.Add(this.groupBox14);
            this.groupBox1.Controls.Add(this.groupBox13);
            this.groupBox1.Controls.Add(this.groupBox12);
            this.groupBox1.Controls.Add(this.tableLayoutPanel2);
            this.groupBox1.Controls.Add(this.groupBox9);
            this.groupBox1.Controls.Add(this.groupBox7);
            this.groupBox1.Controls.Add(this.groupBox6);
            this.groupBox1.Controls.Add(this.groupBox5);
            this.groupBox1.Controls.Add(this.groupBox4);
            this.groupBox1.Controls.Add(this.groupBox3);
            this.groupBox1.Controls.Add(this.tableLayoutPanel1);
            this.groupBox1.Location = new System.Drawing.Point(0, 79);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(942, 677);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Lethality Rating Sheet";
            // 
            // groupBox19
            // 
            this.groupBox19.Controls.Add(this.MostSerious_1);
            this.groupBox19.Controls.Add(this.MostSerious_0);
            this.groupBox19.Controls.Add(this.MostSerious_2);
            this.groupBox19.Controls.Add(this.MostSerious_3);
            this.groupBox19.Location = new System.Drawing.Point(7, 510);
            this.groupBox19.Name = "groupBox19";
            this.groupBox19.Size = new System.Drawing.Size(930, 26);
            this.groupBox19.TabIndex = 18;
            this.groupBox19.TabStop = false;
            this.groupBox19.Text = "Outcome, Most Serious";
            // 
            // MostSerious_1
            // 
            this.MostSerious_1.AutoSize = true;
            this.MostSerious_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostSerious_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostSerious_1.Location = new System.Drawing.Point(595, 8);
            this.MostSerious_1.Name = "MostSerious_1";
            this.MostSerious_1.Size = new System.Drawing.Size(159, 16);
            this.MostSerious_1.TabIndex = 24;
            this.MostSerious_1.TabStop = true;
            this.MostSerious_1.Text = "Emergency Room for Less 24 hrs";
            this.MostSerious_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostSerious_1.UseVisualStyleBackColor = true;
            // 
            // MostSerious_0
            // 
            this.MostSerious_0.AutoSize = true;
            this.MostSerious_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostSerious_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostSerious_0.Location = new System.Drawing.Point(792, 8);
            this.MostSerious_0.Name = "MostSerious_0";
            this.MostSerious_0.Size = new System.Drawing.Size(114, 16);
            this.MostSerious_0.TabIndex = 23;
            this.MostSerious_0.TabStop = true;
            this.MostSerious_0.Text = "No Medical Treatment";
            this.MostSerious_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostSerious_0.UseVisualStyleBackColor = true;
            // 
            // MostSerious_2
            // 
            this.MostSerious_2.AutoSize = true;
            this.MostSerious_2.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostSerious_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostSerious_2.Location = new System.Drawing.Point(424, 8);
            this.MostSerious_2.Name = "MostSerious_2";
            this.MostSerious_2.Size = new System.Drawing.Size(143, 16);
            this.MostSerious_2.TabIndex = 22;
            this.MostSerious_2.TabStop = true;
            this.MostSerious_2.Text = "Medical/Psychiatric Inpatient";
            this.MostSerious_2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostSerious_2.UseVisualStyleBackColor = true;
            // 
            // MostSerious_3
            // 
            this.MostSerious_3.AutoSize = true;
            this.MostSerious_3.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostSerious_3.Location = new System.Drawing.Point(213, 8);
            this.MostSerious_3.Name = "MostSerious_3";
            this.MostSerious_3.Size = new System.Drawing.Size(116, 16);
            this.MostSerious_3.TabIndex = 21;
            this.MostSerious_3.TabStop = true;
            this.MostSerious_3.Text = "ICU/Surgery (3 Points)";
            this.MostSerious_3.UseVisualStyleBackColor = true;
            // 
            // groupBox18
            // 
            this.groupBox18.Controls.Add(this.MostLethal_1);
            this.groupBox18.Controls.Add(this.MostLethal_0);
            this.groupBox18.Controls.Add(this.MostLethal_2);
            this.groupBox18.Controls.Add(this.MostLethal_3);
            this.groupBox18.Location = new System.Drawing.Point(7, 479);
            this.groupBox18.Name = "groupBox18";
            this.groupBox18.Size = new System.Drawing.Size(930, 26);
            this.groupBox18.TabIndex = 17;
            this.groupBox18.TabStop = false;
            this.groupBox18.Text = "Means Used, Most Lethal";
            // 
            // MostLethal_1
            // 
            this.MostLethal_1.AutoSize = true;
            this.MostLethal_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostLethal_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostLethal_1.Location = new System.Drawing.Point(595, 9);
            this.MostLethal_1.Name = "MostLethal_1";
            this.MostLethal_1.Size = new System.Drawing.Size(65, 16);
            this.MostLethal_1.TabIndex = 30;
            this.MostLethal_1.TabStop = true;
            this.MostLethal_1.Text = "Not Lethal";
            this.MostLethal_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostLethal_1.UseVisualStyleBackColor = true;
            // 
            // MostLethal_0
            // 
            this.MostLethal_0.AutoSize = true;
            this.MostLethal_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostLethal_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostLethal_0.Location = new System.Drawing.Point(792, 9);
            this.MostLethal_0.Name = "MostLethal_0";
            this.MostLethal_0.Size = new System.Drawing.Size(45, 16);
            this.MostLethal_0.TabIndex = 29;
            this.MostLethal_0.TabStop = true;
            this.MostLethal_0.Text = "None";
            this.MostLethal_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostLethal_0.UseVisualStyleBackColor = true;
            // 
            // MostLethal_2
            // 
            this.MostLethal_2.AutoSize = true;
            this.MostLethal_2.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostLethal_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostLethal_2.Location = new System.Drawing.Point(424, 9);
            this.MostLethal_2.Name = "MostLethal_2";
            this.MostLethal_2.Size = new System.Drawing.Size(85, 16);
            this.MostLethal_2.TabIndex = 28;
            this.MostLethal_2.TabStop = true;
            this.MostLethal_2.Text = "Possibly Lethal";
            this.MostLethal_2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostLethal_2.UseVisualStyleBackColor = true;
            // 
            // MostLethal_3
            // 
            this.MostLethal_3.AutoSize = true;
            this.MostLethal_3.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostLethal_3.Location = new System.Drawing.Point(213, 9);
            this.MostLethal_3.Name = "MostLethal_3";
            this.MostLethal_3.Size = new System.Drawing.Size(136, 16);
            this.MostLethal_3.TabIndex = 27;
            this.MostLethal_3.TabStop = true;
            this.MostLethal_3.Text = "Likely to be Lethal (3 points)";
            this.MostLethal_3.UseVisualStyleBackColor = true;
            // 
            // groupBox17
            // 
            this.groupBox17.Controls.Add(this.MostRecent_1);
            this.groupBox17.Controls.Add(this.MostRecent_0);
            this.groupBox17.Controls.Add(this.MostRecent_2);
            this.groupBox17.Controls.Add(this.MostRecent_3);
            this.groupBox17.Location = new System.Drawing.Point(7, 448);
            this.groupBox17.Name = "groupBox17";
            this.groupBox17.Size = new System.Drawing.Size(930, 26);
            this.groupBox17.TabIndex = 16;
            this.groupBox17.TabStop = false;
            this.groupBox17.Text = "When Most Recent";
            // 
            // MostRecent_1
            // 
            this.MostRecent_1.AutoSize = true;
            this.MostRecent_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostRecent_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostRecent_1.Location = new System.Drawing.Point(595, 9);
            this.MostRecent_1.Name = "MostRecent_1";
            this.MostRecent_1.Size = new System.Drawing.Size(99, 16);
            this.MostRecent_1.TabIndex = 30;
            this.MostRecent_1.TabStop = true;
            this.MostRecent_1.Text = "Within Past Month";
            this.MostRecent_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostRecent_1.UseVisualStyleBackColor = true;
            // 
            // MostRecent_0
            // 
            this.MostRecent_0.AutoSize = true;
            this.MostRecent_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostRecent_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostRecent_0.Location = new System.Drawing.Point(792, 9);
            this.MostRecent_0.Name = "MostRecent_0";
            this.MostRecent_0.Size = new System.Drawing.Size(111, 16);
            this.MostRecent_0.TabIndex = 29;
            this.MostRecent_0.TabStop = true;
            this.MostRecent_0.Text = "More than a Year Ago";
            this.MostRecent_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostRecent_0.UseVisualStyleBackColor = true;
            // 
            // MostRecent_2
            // 
            this.MostRecent_2.AutoSize = true;
            this.MostRecent_2.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.MostRecent_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostRecent_2.Location = new System.Drawing.Point(424, 9);
            this.MostRecent_2.Name = "MostRecent_2";
            this.MostRecent_2.Size = new System.Drawing.Size(99, 16);
            this.MostRecent_2.TabIndex = 28;
            this.MostRecent_2.TabStop = true;
            this.MostRecent_2.Text = "Within Past Month";
            this.MostRecent_2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.MostRecent_2.UseVisualStyleBackColor = true;
            // 
            // MostRecent_3
            // 
            this.MostRecent_3.AutoSize = true;
            this.MostRecent_3.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostRecent_3.Location = new System.Drawing.Point(213, 9);
            this.MostRecent_3.Name = "MostRecent_3";
            this.MostRecent_3.Size = new System.Drawing.Size(96, 16);
            this.MostRecent_3.TabIndex = 27;
            this.MostRecent_3.TabStop = true;
            this.MostRecent_3.Text = "Within Past Week";
            this.MostRecent_3.UseVisualStyleBackColor = true;
            // 
            // groupBox11
            // 
            this.groupBox11.Controls.Add(this.Supports_0);
            this.groupBox11.Controls.Add(this.Supports_2);
            this.groupBox11.Controls.Add(this.Supports_1);
            this.groupBox11.Location = new System.Drawing.Point(7, 386);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new System.Drawing.Size(930, 26);
            this.groupBox11.TabIndex = 9;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Supports";
            // 
            // Supports_0
            // 
            this.Supports_0.AutoSize = true;
            this.Supports_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Supports_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Supports_0.Location = new System.Drawing.Point(792, 8);
            this.Supports_0.Name = "Supports_0";
            this.Supports_0.Size = new System.Drawing.Size(86, 16);
            this.Supports_0.TabIndex = 32;
            this.Supports_0.TabStop = true;
            this.Supports_0.Text = "Strong or Many";
            this.Supports_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Supports_0.UseVisualStyleBackColor = true;
            // 
            // Supports_2
            // 
            this.Supports_2.AutoSize = true;
            this.Supports_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Supports_2.Location = new System.Drawing.Point(424, 8);
            this.Supports_2.Name = "Supports_2";
            this.Supports_2.Size = new System.Drawing.Size(67, 16);
            this.Supports_2.TabIndex = 30;
            this.Supports_2.TabStop = true;
            this.Supports_2.Text = "Conflictual";
            this.Supports_2.UseVisualStyleBackColor = true;
            // 
            // Supports_1
            // 
            this.Supports_1.AutoSize = true;
            this.Supports_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Supports_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Supports_1.Location = new System.Drawing.Point(595, 8);
            this.Supports_1.Name = "Supports_1";
            this.Supports_1.Size = new System.Drawing.Size(94, 16);
            this.Supports_1.TabIndex = 31;
            this.Supports_1.TabStop = true;
            this.Supports_1.Text = "Moderate or Few";
            this.Supports_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Supports_1.UseVisualStyleBackColor = true;
            // 
            // groupBox10
            // 
            this.groupBox10.Controls.Add(this.DepressionSymptoms_0);
            this.groupBox10.Controls.Add(this.DepressionSymptoms_1);
            this.groupBox10.Controls.Add(this.DepressionSymptoms_2);
            this.groupBox10.Location = new System.Drawing.Point(7, 355);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(930, 26);
            this.groupBox10.TabIndex = 8;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "Depression Attempts";
            // 
            // DepressionSymptoms_0
            // 
            this.DepressionSymptoms_0.AutoSize = true;
            this.DepressionSymptoms_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.DepressionSymptoms_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DepressionSymptoms_0.Location = new System.Drawing.Point(792, 9);
            this.DepressionSymptoms_0.Name = "DepressionSymptoms_0";
            this.DepressionSymptoms_0.Size = new System.Drawing.Size(45, 16);
            this.DepressionSymptoms_0.TabIndex = 29;
            this.DepressionSymptoms_0.TabStop = true;
            this.DepressionSymptoms_0.Text = "None";
            this.DepressionSymptoms_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.DepressionSymptoms_0.UseVisualStyleBackColor = true;
            // 
            // DepressionSymptoms_1
            // 
            this.DepressionSymptoms_1.AutoSize = true;
            this.DepressionSymptoms_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.DepressionSymptoms_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DepressionSymptoms_1.Location = new System.Drawing.Point(595, 9);
            this.DepressionSymptoms_1.Name = "DepressionSymptoms_1";
            this.DepressionSymptoms_1.Size = new System.Drawing.Size(47, 16);
            this.DepressionSymptoms_1.TabIndex = 28;
            this.DepressionSymptoms_1.TabStop = true;
            this.DepressionSymptoms_1.Text = "Some";
            this.DepressionSymptoms_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.DepressionSymptoms_1.UseVisualStyleBackColor = true;
            // 
            // DepressionSymptoms_2
            // 
            this.DepressionSymptoms_2.AutoSize = true;
            this.DepressionSymptoms_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DepressionSymptoms_2.Location = new System.Drawing.Point(424, 9);
            this.DepressionSymptoms_2.Name = "DepressionSymptoms_2";
            this.DepressionSymptoms_2.Size = new System.Drawing.Size(47, 16);
            this.DepressionSymptoms_2.TabIndex = 27;
            this.DepressionSymptoms_2.TabStop = true;
            this.DepressionSymptoms_2.Text = "Many";
            this.DepressionSymptoms_2.UseVisualStyleBackColor = true;
            // 
            // groupBox8
            // 
            this.groupBox8.Controls.Add(this.PriorAttempts_0);
            this.groupBox8.Controls.Add(this.PriorAttempts_1);
            this.groupBox8.Controls.Add(this.PriorAttempts_2);
            this.groupBox8.Location = new System.Drawing.Point(7, 417);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(930, 26);
            this.groupBox8.TabIndex = 6;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "Prior Attempts";
            // 
            // PriorAttempts_0
            // 
            this.PriorAttempts_0.AutoSize = true;
            this.PriorAttempts_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.PriorAttempts_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriorAttempts_0.Location = new System.Drawing.Point(792, 8);
            this.PriorAttempts_0.Name = "PriorAttempts_0";
            this.PriorAttempts_0.Size = new System.Drawing.Size(45, 16);
            this.PriorAttempts_0.TabIndex = 23;
            this.PriorAttempts_0.TabStop = true;
            this.PriorAttempts_0.Text = "None";
            this.PriorAttempts_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.PriorAttempts_0.UseVisualStyleBackColor = true;
            // 
            // PriorAttempts_1
            // 
            this.PriorAttempts_1.AutoSize = true;
            this.PriorAttempts_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.PriorAttempts_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriorAttempts_1.Location = new System.Drawing.Point(595, 8);
            this.PriorAttempts_1.Name = "PriorAttempts_1";
            this.PriorAttempts_1.Size = new System.Drawing.Size(45, 16);
            this.PriorAttempts_1.TabIndex = 22;
            this.PriorAttempts_1.TabStop = true;
            this.PriorAttempts_1.Text = "1 or 2";
            this.PriorAttempts_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.PriorAttempts_1.UseVisualStyleBackColor = true;
            // 
            // PriorAttempts_2
            // 
            this.PriorAttempts_2.AutoSize = true;
            this.PriorAttempts_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriorAttempts_2.Location = new System.Drawing.Point(424, 8);
            this.PriorAttempts_2.Name = "PriorAttempts_2";
            this.PriorAttempts_2.Size = new System.Drawing.Size(74, 16);
            this.PriorAttempts_2.TabIndex = 21;
            this.PriorAttempts_2.TabStop = true;
            this.PriorAttempts_2.Text = "More Than 2";
            this.PriorAttempts_2.UseVisualStyleBackColor = true;
            // 
            // groupBox16
            // 
            this.groupBox16.Controls.Add(this.Alternatives_0);
            this.groupBox16.Controls.Add(this.Alternatives_1);
            this.groupBox16.Controls.Add(this.Alternatives_2);
            this.groupBox16.Location = new System.Drawing.Point(7, 231);
            this.groupBox16.Name = "groupBox16";
            this.groupBox16.Size = new System.Drawing.Size(930, 26);
            this.groupBox16.TabIndex = 15;
            this.groupBox16.TabStop = false;
            this.groupBox16.Text = "Recognizes Alternatives to Act";
            // 
            // Alternatives_0
            // 
            this.Alternatives_0.AutoSize = true;
            this.Alternatives_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Alternatives_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Alternatives_0.Location = new System.Drawing.Point(792, 9);
            this.Alternatives_0.Name = "Alternatives_0";
            this.Alternatives_0.Size = new System.Drawing.Size(38, 16);
            this.Alternatives_0.TabIndex = 17;
            this.Alternatives_0.TabStop = true;
            this.Alternatives_0.Text = "Yes";
            this.Alternatives_0.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.Alternatives_0.UseVisualStyleBackColor = true;
            // 
            // Alternatives_1
            // 
            this.Alternatives_1.AutoSize = true;
            this.Alternatives_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Alternatives_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Alternatives_1.Location = new System.Drawing.Point(595, 9);
            this.Alternatives_1.Name = "Alternatives_1";
            this.Alternatives_1.Size = new System.Drawing.Size(82, 16);
            this.Alternatives_1.TabIndex = 16;
            this.Alternatives_1.TabStop = true;
            this.Alternatives_1.Text = "Hypothetically";
            this.Alternatives_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Alternatives_1.UseVisualStyleBackColor = true;
            // 
            // Alternatives_2
            // 
            this.Alternatives_2.AutoSize = true;
            this.Alternatives_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Alternatives_2.Location = new System.Drawing.Point(424, 9);
            this.Alternatives_2.Name = "Alternatives_2";
            this.Alternatives_2.Size = new System.Drawing.Size(35, 16);
            this.Alternatives_2.TabIndex = 15;
            this.Alternatives_2.TabStop = true;
            this.Alternatives_2.Text = "No";
            this.Alternatives_2.UseVisualStyleBackColor = true;
            // 
            // groupBox15
            // 
            this.groupBox15.Controls.Add(this.Consequences_0);
            this.groupBox15.Controls.Add(this.Consequences_1);
            this.groupBox15.Controls.Add(this.Consequences_2);
            this.groupBox15.Location = new System.Drawing.Point(7, 200);
            this.groupBox15.Name = "groupBox15";
            this.groupBox15.Size = new System.Drawing.Size(930, 26);
            this.groupBox15.TabIndex = 14;
            this.groupBox15.TabStop = false;
            this.groupBox15.Text = "Prepared for Consequences of Act";
            // 
            // Consequences_0
            // 
            this.Consequences_0.AutoSize = true;
            this.Consequences_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Consequences_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Consequences_0.Location = new System.Drawing.Point(792, 9);
            this.Consequences_0.Name = "Consequences_0";
            this.Consequences_0.Size = new System.Drawing.Size(35, 16);
            this.Consequences_0.TabIndex = 17;
            this.Consequences_0.TabStop = true;
            this.Consequences_0.Text = "No";
            this.Consequences_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Consequences_0.UseVisualStyleBackColor = true;
            // 
            // Consequences_1
            // 
            this.Consequences_1.AutoSize = true;
            this.Consequences_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Consequences_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Consequences_1.Location = new System.Drawing.Point(595, 9);
            this.Consequences_1.Name = "Consequences_1";
            this.Consequences_1.Size = new System.Drawing.Size(59, 16);
            this.Consequences_1.TabIndex = 16;
            this.Consequences_1.TabStop = true;
            this.Consequences_1.Text = "Not Sure";
            this.Consequences_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Consequences_1.UseVisualStyleBackColor = true;
            // 
            // Consequences_2
            // 
            this.Consequences_2.AutoSize = true;
            this.Consequences_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Consequences_2.Location = new System.Drawing.Point(424, 9);
            this.Consequences_2.Name = "Consequences_2";
            this.Consequences_2.Size = new System.Drawing.Size(70, 16);
            this.Consequences_2.TabIndex = 15;
            this.Consequences_2.TabStop = true;
            this.Consequences_2.Text = "Completely";
            this.Consequences_2.UseVisualStyleBackColor = true;
            // 
            // groupBox14
            // 
            this.groupBox14.Controls.Add(this.FeelsJustified_0);
            this.groupBox14.Controls.Add(this.FeelsJustified_1);
            this.groupBox14.Controls.Add(this.FeelsJustified_2);
            this.groupBox14.Location = new System.Drawing.Point(7, 169);
            this.groupBox14.Name = "groupBox14";
            this.groupBox14.Size = new System.Drawing.Size(930, 26);
            this.groupBox14.TabIndex = 13;
            this.groupBox14.TabStop = false;
            this.groupBox14.Text = "Feels Justified in Doing Act";
            // 
            // FeelsJustified_0
            // 
            this.FeelsJustified_0.AutoSize = true;
            this.FeelsJustified_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.FeelsJustified_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FeelsJustified_0.Location = new System.Drawing.Point(792, 9);
            this.FeelsJustified_0.Name = "FeelsJustified_0";
            this.FeelsJustified_0.Size = new System.Drawing.Size(63, 16);
            this.FeelsJustified_0.TabIndex = 17;
            this.FeelsJustified_0.TabStop = true;
            this.FeelsJustified_0.Text = "Not At All";
            this.FeelsJustified_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.FeelsJustified_0.UseVisualStyleBackColor = true;
            // 
            // FeelsJustified_1
            // 
            this.FeelsJustified_1.AutoSize = true;
            this.FeelsJustified_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.FeelsJustified_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FeelsJustified_1.Location = new System.Drawing.Point(595, 9);
            this.FeelsJustified_1.Name = "FeelsJustified_1";
            this.FeelsJustified_1.Size = new System.Drawing.Size(68, 16);
            this.FeelsJustified_1.TabIndex = 16;
            this.FeelsJustified_1.TabStop = true;
            this.FeelsJustified_1.Text = "Somewhat";
            this.FeelsJustified_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.FeelsJustified_1.UseVisualStyleBackColor = true;
            // 
            // FeelsJustified_2
            // 
            this.FeelsJustified_2.AutoSize = true;
            this.FeelsJustified_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FeelsJustified_2.Location = new System.Drawing.Point(424, 9);
            this.FeelsJustified_2.Name = "FeelsJustified_2";
            this.FeelsJustified_2.Size = new System.Drawing.Size(129, 16);
            this.FeelsJustified_2.TabIndex = 15;
            this.FeelsJustified_2.TabStop = true;
            this.FeelsJustified_2.Text = "Completely/No Ambiguity";
            this.FeelsJustified_2.UseVisualStyleBackColor = true;
            // 
            // groupBox13
            // 
            this.groupBox13.Controls.Add(this.CallerAlone_0);
            this.groupBox13.Controls.Add(this.CallerAlone_1);
            this.groupBox13.Controls.Add(this.CallerAlone_2);
            this.groupBox13.Location = new System.Drawing.Point(7, 262);
            this.groupBox13.Name = "groupBox13";
            this.groupBox13.Size = new System.Drawing.Size(930, 26);
            this.groupBox13.TabIndex = 12;
            this.groupBox13.TabStop = false;
            this.groupBox13.Text = "Caller Alone";
            // 
            // CallerAlone_0
            // 
            this.CallerAlone_0.AutoSize = true;
            this.CallerAlone_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.CallerAlone_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CallerAlone_0.Location = new System.Drawing.Point(792, 9);
            this.CallerAlone_0.Name = "CallerAlone_0";
            this.CallerAlone_0.Size = new System.Drawing.Size(35, 16);
            this.CallerAlone_0.TabIndex = 17;
            this.CallerAlone_0.TabStop = true;
            this.CallerAlone_0.Text = "No";
            this.CallerAlone_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.CallerAlone_0.UseVisualStyleBackColor = true;
            // 
            // CallerAlone_1
            // 
            this.CallerAlone_1.AutoSize = true;
            this.CallerAlone_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.CallerAlone_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CallerAlone_1.Location = new System.Drawing.Point(595, 9);
            this.CallerAlone_1.Name = "CallerAlone_1";
            this.CallerAlone_1.Size = new System.Drawing.Size(123, 16);
            this.CallerAlone_1.TabIndex = 16;
            this.CallerAlone_1.TabStop = true;
            this.CallerAlone_1.Text = "Yes, expecting someone";
            this.CallerAlone_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.CallerAlone_1.UseVisualStyleBackColor = true;
            // 
            // CallerAlone_2
            // 
            this.CallerAlone_2.AutoSize = true;
            this.CallerAlone_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CallerAlone_2.Location = new System.Drawing.Point(424, 9);
            this.CallerAlone_2.Name = "CallerAlone_2";
            this.CallerAlone_2.Size = new System.Drawing.Size(38, 16);
            this.CallerAlone_2.TabIndex = 15;
            this.CallerAlone_2.TabStop = true;
            this.CallerAlone_2.Text = "Yes";
            this.CallerAlone_2.UseVisualStyleBackColor = true;
            // 
            // groupBox12
            // 
            this.groupBox12.Controls.Add(this.Comments);
            this.groupBox12.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.groupBox12.Location = new System.Drawing.Point(3, 613);
            this.groupBox12.Name = "groupBox12";
            this.groupBox12.Size = new System.Drawing.Size(936, 61);
            this.groupBox12.TabIndex = 11;
            this.groupBox12.TabStop = false;
            this.groupBox12.Text = "Additional Comments:";
            // 
            // Comments
            // 
            this.Comments.Location = new System.Drawing.Point(3, 19);
            this.Comments.Multiline = true;
            this.Comments.Name = "Comments";
            this.Comments.Size = new System.Drawing.Size(927, 39);
            this.Comments.TabIndex = 12;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.tableLayoutPanel2.ColumnCount = 4;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 23.89666F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25.94187F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel2.Controls.Add(this.label6, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.label5, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.Total2, 2, 0);
            this.tableLayoutPanel2.Controls.Add(this.Total1, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.Score, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.Total3, 3, 0);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(6, 552);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 2;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(930, 55);
            this.tableLayoutPanel2.TabIndex = 10;
            // 
            // label6
            // 
            this.label6.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(99, 34);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(35, 13);
            this.label6.TabIndex = 4;
            this.label6.Text = "Score";
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(98, 7);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(36, 13);
            this.label5.TabIndex = 0;
            this.label5.Text = "Totals";
            // 
            // Total2
            // 
            this.Total2.Location = new System.Drawing.Point(458, 4);
            this.Total2.Name = "Total2";
            this.Total2.Size = new System.Drawing.Size(145, 20);
            this.Total2.TabIndex = 2;
            // 
            // Total1
            // 
            this.Total1.Location = new System.Drawing.Point(236, 4);
            this.Total1.Name = "Total1";
            this.Total1.Size = new System.Drawing.Size(145, 20);
            this.Total1.TabIndex = 1;
            // 
            // Score
            // 
            this.Score.Location = new System.Drawing.Point(236, 31);
            this.Score.Name = "Score";
            this.Score.Size = new System.Drawing.Size(145, 20);
            this.Score.TabIndex = 5;
            // 
            // Total3
            // 
            this.Total3.Location = new System.Drawing.Point(699, 4);
            this.Total3.Name = "Total3";
            this.Total3.Size = new System.Drawing.Size(145, 20);
            this.Total3.TabIndex = 3;
            // 
            // groupBox9
            // 
            this.groupBox9.Controls.Add(this.FamilyAttemptsCompletions_3);
            this.groupBox9.Controls.Add(this.FamilyAttemptsCompletions_0);
            this.groupBox9.Controls.Add(this.FamilyAttemptsCompletions_1);
            this.groupBox9.Controls.Add(this.FamilyAttemptsCompletions_2);
            this.groupBox9.Location = new System.Drawing.Point(7, 324);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(930, 26);
            this.groupBox9.TabIndex = 7;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Family Attempts/Completions";
            // 
            // FamilyAttemptsCompletions_3
            // 
            this.FamilyAttemptsCompletions_3.AutoSize = true;
            this.FamilyAttemptsCompletions_3.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FamilyAttemptsCompletions_3.Location = new System.Drawing.Point(213, 8);
            this.FamilyAttemptsCompletions_3.Name = "FamilyAttemptsCompletions_3";
            this.FamilyAttemptsCompletions_3.Size = new System.Drawing.Size(134, 16);
            this.FamilyAttemptsCompletions_3.TabIndex = 27;
            this.FamilyAttemptsCompletions_3.TabStop = true;
            this.FamilyAttemptsCompletions_3.Text = "Immediate Family Member";
            this.FamilyAttemptsCompletions_3.UseVisualStyleBackColor = true;
            // 
            // FamilyAttemptsCompletions_0
            // 
            this.FamilyAttemptsCompletions_0.AutoSize = true;
            this.FamilyAttemptsCompletions_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.FamilyAttemptsCompletions_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FamilyAttemptsCompletions_0.Location = new System.Drawing.Point(792, 8);
            this.FamilyAttemptsCompletions_0.Name = "FamilyAttemptsCompletions_0";
            this.FamilyAttemptsCompletions_0.Size = new System.Drawing.Size(45, 16);
            this.FamilyAttemptsCompletions_0.TabIndex = 26;
            this.FamilyAttemptsCompletions_0.TabStop = true;
            this.FamilyAttemptsCompletions_0.Text = "None";
            this.FamilyAttemptsCompletions_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.FamilyAttemptsCompletions_0.UseVisualStyleBackColor = true;
            // 
            // FamilyAttemptsCompletions_1
            // 
            this.FamilyAttemptsCompletions_1.AutoSize = true;
            this.FamilyAttemptsCompletions_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.FamilyAttemptsCompletions_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FamilyAttemptsCompletions_1.Location = new System.Drawing.Point(595, 8);
            this.FamilyAttemptsCompletions_1.Name = "FamilyAttemptsCompletions_1";
            this.FamilyAttemptsCompletions_1.Size = new System.Drawing.Size(130, 16);
            this.FamilyAttemptsCompletions_1.TabIndex = 25;
            this.FamilyAttemptsCompletions_1.TabStop = true;
            this.FamilyAttemptsCompletions_1.Text = "Extended Family or Friend";
            this.FamilyAttemptsCompletions_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.FamilyAttemptsCompletions_1.UseVisualStyleBackColor = true;
            // 
            // FamilyAttemptsCompletions_2
            // 
            this.FamilyAttemptsCompletions_2.AutoSize = true;
            this.FamilyAttemptsCompletions_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FamilyAttemptsCompletions_2.Location = new System.Drawing.Point(424, 8);
            this.FamilyAttemptsCompletions_2.Name = "FamilyAttemptsCompletions_2";
            this.FamilyAttemptsCompletions_2.Size = new System.Drawing.Size(97, 16);
            this.FamilyAttemptsCompletions_2.TabIndex = 24;
            this.FamilyAttemptsCompletions_2.TabStop = true;
            this.FamilyAttemptsCompletions_2.Text = "Immediate Family";
            this.FamilyAttemptsCompletions_2.UseVisualStyleBackColor = true;
            // 
            // groupBox7
            // 
            this.groupBox7.Controls.Add(this.DrugAlcoholUse_10);
            this.groupBox7.Controls.Add(this.DrugAlcoholUse_0);
            this.groupBox7.Controls.Add(this.DrugAlcoholUse_1);
            this.groupBox7.Controls.Add(this.DrugAlcoholUse_2);
            this.groupBox7.Location = new System.Drawing.Point(7, 293);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(930, 26);
            this.groupBox7.TabIndex = 5;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Drug Alcohol Use";
            // 
            // DrugAlcoholUse_10
            // 
            this.DrugAlcoholUse_10.AutoSize = true;
            this.DrugAlcoholUse_10.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DrugAlcoholUse_10.Location = new System.Drawing.Point(213, 7);
            this.DrugAlcoholUse_10.Name = "DrugAlcoholUse_10";
            this.DrugAlcoholUse_10.Size = new System.Drawing.Size(128, 16);
            this.DrugAlcoholUse_10.TabIndex = 21;
            this.DrugAlcoholUse_10.TabStop = true;
            this.DrugAlcoholUse_10.Text = "Currently Under Influence";
            this.DrugAlcoholUse_10.UseVisualStyleBackColor = true;
            // 
            // DrugAlcoholUse_0
            // 
            this.DrugAlcoholUse_0.AutoSize = true;
            this.DrugAlcoholUse_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.DrugAlcoholUse_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DrugAlcoholUse_0.Location = new System.Drawing.Point(792, 7);
            this.DrugAlcoholUse_0.Name = "DrugAlcoholUse_0";
            this.DrugAlcoholUse_0.Size = new System.Drawing.Size(54, 16);
            this.DrugAlcoholUse_0.TabIndex = 20;
            this.DrugAlcoholUse_0.TabStop = true;
            this.DrugAlcoholUse_0.Text = "No Use";
            this.DrugAlcoholUse_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.DrugAlcoholUse_0.UseVisualStyleBackColor = true;
            // 
            // DrugAlcoholUse_1
            // 
            this.DrugAlcoholUse_1.AutoSize = true;
            this.DrugAlcoholUse_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.DrugAlcoholUse_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DrugAlcoholUse_1.Location = new System.Drawing.Point(595, 7);
            this.DrugAlcoholUse_1.Name = "DrugAlcoholUse_1";
            this.DrugAlcoholUse_1.Size = new System.Drawing.Size(45, 16);
            this.DrugAlcoholUse_1.TabIndex = 19;
            this.DrugAlcoholUse_1.TabStop = true;
            this.DrugAlcoholUse_1.Text = "Uses";
            this.DrugAlcoholUse_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.DrugAlcoholUse_1.UseVisualStyleBackColor = true;
            // 
            // DrugAlcoholUse_2
            // 
            this.DrugAlcoholUse_2.AutoSize = true;
            this.DrugAlcoholUse_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DrugAlcoholUse_2.Location = new System.Drawing.Point(424, 7);
            this.DrugAlcoholUse_2.Name = "DrugAlcoholUse_2";
            this.DrugAlcoholUse_2.Size = new System.Drawing.Size(88, 16);
            this.DrugAlcoholUse_2.TabIndex = 18;
            this.DrugAlcoholUse_2.TabStop = true;
            this.DrugAlcoholUse_2.Text = "Under Influence";
            this.DrugAlcoholUse_2.UseVisualStyleBackColor = true;
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.Ability_0);
            this.groupBox6.Controls.Add(this.Ability_1);
            this.groupBox6.Controls.Add(this.Ability_2);
            this.groupBox6.Location = new System.Drawing.Point(7, 138);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(930, 26);
            this.groupBox6.TabIndex = 4;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Ability";
            // 
            // Ability_0
            // 
            this.Ability_0.AutoSize = true;
            this.Ability_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Ability_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Ability_0.Location = new System.Drawing.Point(792, 9);
            this.Ability_0.Name = "Ability_0";
            this.Ability_0.Size = new System.Drawing.Size(35, 16);
            this.Ability_0.TabIndex = 17;
            this.Ability_0.TabStop = true;
            this.Ability_0.Text = "No";
            this.Ability_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Ability_0.UseVisualStyleBackColor = true;
            // 
            // Ability_1
            // 
            this.Ability_1.AutoSize = true;
            this.Ability_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Ability_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Ability_1.Location = new System.Drawing.Point(595, 9);
            this.Ability_1.Name = "Ability_1";
            this.Ability_1.Size = new System.Drawing.Size(123, 16);
            this.Ability_1.TabIndex = 16;
            this.Ability_1.TabStop = true;
            this.Ability_1.Text = "Yes, expecting someone";
            this.Ability_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Ability_1.UseVisualStyleBackColor = true;
            // 
            // Ability_2
            // 
            this.Ability_2.AutoSize = true;
            this.Ability_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Ability_2.Location = new System.Drawing.Point(424, 9);
            this.Ability_2.Name = "Ability_2";
            this.Ability_2.Size = new System.Drawing.Size(67, 16);
            this.Ability_2.TabIndex = 15;
            this.Ability_2.TabStop = true;
            this.Ability_2.Text = "Immediate";
            this.Ability_2.UseVisualStyleBackColor = true;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.Accessibility_0);
            this.groupBox5.Controls.Add(this.Accessibility_1);
            this.groupBox5.Controls.Add(this.Accessibility_2);
            this.groupBox5.Location = new System.Drawing.Point(7, 107);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(930, 26);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Accessibility";
            // 
            // Accessibility_0
            // 
            this.Accessibility_0.AutoSize = true;
            this.Accessibility_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Accessibility_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Accessibility_0.Location = new System.Drawing.Point(792, 7);
            this.Accessibility_0.Name = "Accessibility_0";
            this.Accessibility_0.Size = new System.Drawing.Size(119, 16);
            this.Accessibility_0.TabIndex = 14;
            this.Accessibility_0.TabStop = true;
            this.Accessibility_0.Text = "Not Readily Accessible";
            this.Accessibility_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Accessibility_0.UseVisualStyleBackColor = true;
            // 
            // Accessibility_1
            // 
            this.Accessibility_1.AutoSize = true;
            this.Accessibility_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Accessibility_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Accessibility_1.Location = new System.Drawing.Point(595, 7);
            this.Accessibility_1.Name = "Accessibility_1";
            this.Accessibility_1.Size = new System.Drawing.Size(145, 16);
            this.Accessibility_1.TabIndex = 13;
            this.Accessibility_1.TabStop = true;
            this.Accessibility_1.Text = "Can Access Within 5 Minutes";
            this.Accessibility_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Accessibility_1.UseVisualStyleBackColor = true;
            // 
            // Accessibility_2
            // 
            this.Accessibility_2.AutoSize = true;
            this.Accessibility_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Accessibility_2.Location = new System.Drawing.Point(424, 7);
            this.Accessibility_2.Name = "Accessibility_2";
            this.Accessibility_2.Size = new System.Drawing.Size(78, 16);
            this.Accessibility_2.TabIndex = 12;
            this.Accessibility_2.TabStop = true;
            this.Accessibility_2.Text = "Within Reach";
            this.Accessibility_2.UseVisualStyleBackColor = true;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.Method_10);
            this.groupBox4.Controls.Add(this.Method_0);
            this.groupBox4.Controls.Add(this.Method_1);
            this.groupBox4.Controls.Add(this.Method_2);
            this.groupBox4.Location = new System.Drawing.Point(7, 76);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(930, 26);
            this.groupBox4.TabIndex = 2;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Method";
            // 
            // Method_10
            // 
            this.Method_10.AutoSize = true;
            this.Method_10.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Method_10.Location = new System.Drawing.Point(213, 8);
            this.Method_10.Name = "Method_10";
            this.Method_10.Size = new System.Drawing.Size(129, 16);
            this.Method_10.TabIndex = 12;
            this.Method_10.TabStop = true;
            this.Method_10.Text = "Likely to be Quickly Lethal";
            this.Method_10.UseVisualStyleBackColor = true;
            // 
            // Method_0
            // 
            this.Method_0.AutoSize = true;
            this.Method_0.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Method_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Method_0.Location = new System.Drawing.Point(792, 8);
            this.Method_0.Name = "Method_0";
            this.Method_0.Size = new System.Drawing.Size(91, 16);
            this.Method_0.TabIndex = 11;
            this.Method_0.TabStop = true;
            this.Method_0.Text = "Not Likely Lethal";
            this.Method_0.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Method_0.UseVisualStyleBackColor = true;
            // 
            // Method_1
            // 
            this.Method_1.AutoSize = true;
            this.Method_1.CheckAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Method_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Method_1.Location = new System.Drawing.Point(595, 8);
            this.Method_1.Name = "Method_1";
            this.Method_1.Size = new System.Drawing.Size(113, 16);
            this.Method_1.TabIndex = 10;
            this.Method_1.TabStop = true;
            this.Method_1.Text = "Likely To Cause Injury";
            this.Method_1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.Method_1.UseVisualStyleBackColor = true;
            // 
            // Method_2
            // 
            this.Method_2.AutoSize = true;
            this.Method_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Method_2.Location = new System.Drawing.Point(424, 8);
            this.Method_2.Name = "Method_2";
            this.Method_2.Size = new System.Drawing.Size(85, 16);
            this.Method_2.TabIndex = 9;
            this.Method_2.TabStop = true;
            this.Method_2.Text = "Possible Lethal";
            this.Method_2.UseVisualStyleBackColor = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.PlanSelect_0);
            this.groupBox3.Controls.Add(this.PlanSelect_1);
            this.groupBox3.Controls.Add(this.PlanSelect_2);
            this.groupBox3.Location = new System.Drawing.Point(7, 45);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(930, 26);
            this.groupBox3.TabIndex = 1;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Plan";
            // 
            // PlanSelect_0
            // 
            this.PlanSelect_0.AutoSize = true;
            this.PlanSelect_0.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PlanSelect_0.Location = new System.Drawing.Point(792, 7);
            this.PlanSelect_0.Name = "PlanSelect_0";
            this.PlanSelect_0.Size = new System.Drawing.Size(45, 16);
            this.PlanSelect_0.TabIndex = 8;
            this.PlanSelect_0.TabStop = true;
            this.PlanSelect_0.Text = "None";
            this.PlanSelect_0.UseVisualStyleBackColor = true;
            // 
            // PlanSelect_1
            // 
            this.PlanSelect_1.AutoSize = true;
            this.PlanSelect_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PlanSelect_1.Location = new System.Drawing.Point(595, 7);
            this.PlanSelect_1.Name = "PlanSelect_1";
            this.PlanSelect_1.Size = new System.Drawing.Size(50, 16);
            this.PlanSelect_1.TabIndex = 7;
            this.PlanSelect_1.TabStop = true;
            this.PlanSelect_1.Text = "Vague";
            this.PlanSelect_1.UseVisualStyleBackColor = true;
            // 
            // PlanSelect_2
            // 
            this.PlanSelect_2.AutoSize = true;
            this.PlanSelect_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PlanSelect_2.Location = new System.Drawing.Point(424, 7);
            this.PlanSelect_2.Name = "PlanSelect_2";
            this.PlanSelect_2.Size = new System.Drawing.Size(56, 16);
            this.PlanSelect_2.TabIndex = 6;
            this.PlanSelect_2.TabStop = true;
            this.PlanSelect_2.Text = "Specific";
            this.PlanSelect_2.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.tableLayoutPanel1.ColumnCount = 5;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.Controls.Add(this.label7, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.label8, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.label4, 4, 0);
            this.tableLayoutPanel1.Controls.Add(this.label3, 3, 0);
            this.tableLayoutPanel1.Controls.Add(this.label2, 2, 0);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(6, 16);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(930, 26);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // label7
            // 
            this.label7.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(255, 6);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(45, 13);
            this.label7.TabIndex = 4;
            this.label7.Text = "Variable";
            // 
            // label8
            // 
            this.label8.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(75, 6);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(36, 13);
            this.label8.TabIndex = 3;
            this.label8.Text = "Points";
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(828, 6);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(13, 13);
            this.label4.TabIndex = 2;
            this.label4.Text = "0";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(641, 6);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(13, 13);
            this.label3.TabIndex = 1;
            this.label3.Text = "1";
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(456, 6);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(13, 13);
            this.label2.TabIndex = 0;
            this.label2.Text = "2";
            // 
            // NewLethalityFormView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.toolStrip1);
            this.Name = "NewLethalityFormView";
            this.Size = new System.Drawing.Size(948, 759);
            this.Load += new System.EventHandler(this.NewLethalityFormView_Load);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox19.ResumeLayout(false);
            this.groupBox19.PerformLayout();
            this.groupBox18.ResumeLayout(false);
            this.groupBox18.PerformLayout();
            this.groupBox17.ResumeLayout(false);
            this.groupBox17.PerformLayout();
            this.groupBox11.ResumeLayout(false);
            this.groupBox11.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.groupBox16.ResumeLayout(false);
            this.groupBox16.PerformLayout();
            this.groupBox15.ResumeLayout(false);
            this.groupBox15.PerformLayout();
            this.groupBox14.ResumeLayout(false);
            this.groupBox14.PerformLayout();
            this.groupBox13.ResumeLayout(false);
            this.groupBox13.PerformLayout();
            this.groupBox12.ResumeLayout(false);
            this.groupBox12.PerformLayout();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton SaveToolStripButton;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label ClientDOBlbl;
        private System.Windows.Forms.TextBox PfirstName;
        private System.Windows.Forms.TextBox PlastName;
        private System.Windows.Forms.Label ClientLName;
        private System.Windows.Forms.Label ClientFName;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox Time;
        private System.Windows.Forms.TextBox Date;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.GroupBox groupBox11;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TextBox Total3;
        private System.Windows.Forms.TextBox Total2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox Total1;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox Score;
        private System.Windows.Forms.RadioButton PlanSelect_0;
        private System.Windows.Forms.RadioButton PlanSelect_1;
        private System.Windows.Forms.RadioButton PlanSelect_2;
        private System.Windows.Forms.RadioButton Method_0;
        private System.Windows.Forms.RadioButton Method_1;
        private System.Windows.Forms.RadioButton Method_2;
        private System.Windows.Forms.RadioButton Ability_0;
        private System.Windows.Forms.RadioButton Ability_1;
        private System.Windows.Forms.RadioButton Ability_2;
        private System.Windows.Forms.RadioButton Accessibility_0;
        private System.Windows.Forms.RadioButton Accessibility_1;
        private System.Windows.Forms.RadioButton Accessibility_2;
        private System.Windows.Forms.RadioButton DrugAlcoholUse_0;
        private System.Windows.Forms.RadioButton DrugAlcoholUse_1;
        private System.Windows.Forms.RadioButton DrugAlcoholUse_2;
        private System.Windows.Forms.RadioButton PriorAttempts_0;
        private System.Windows.Forms.RadioButton PriorAttempts_1;
        private System.Windows.Forms.RadioButton PriorAttempts_2;
        private System.Windows.Forms.RadioButton DepressionSymptoms_0;
        private System.Windows.Forms.RadioButton DepressionSymptoms_1;
        private System.Windows.Forms.RadioButton DepressionSymptoms_2;
        private System.Windows.Forms.RadioButton FamilyAttemptsCompletions_0;
        private System.Windows.Forms.RadioButton FamilyAttemptsCompletions_1;
        private System.Windows.Forms.RadioButton FamilyAttemptsCompletions_2;
        private System.Windows.Forms.RadioButton Supports_0;
        private System.Windows.Forms.RadioButton Supports_2;
        private System.Windows.Forms.RadioButton Supports_1;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.GroupBox groupBox12;
        private System.Windows.Forms.TextBox Comments;
        private System.Windows.Forms.ComboBox CaseNumber;
        private System.Windows.Forms.TextBox Employee;
        private System.Windows.Forms.Label Employeelbl;
        private System.Windows.Forms.RadioButton Method_10;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.GroupBox groupBox13;
        private System.Windows.Forms.RadioButton CallerAlone_0;
        private System.Windows.Forms.RadioButton CallerAlone_1;
        private System.Windows.Forms.RadioButton CallerAlone_2;
        private System.Windows.Forms.GroupBox groupBox14;
        private System.Windows.Forms.RadioButton FeelsJustified_0;
        private System.Windows.Forms.RadioButton FeelsJustified_1;
        private System.Windows.Forms.RadioButton FeelsJustified_2;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.RadioButton Consequences_0;
        private System.Windows.Forms.RadioButton Consequences_1;
        private System.Windows.Forms.RadioButton Consequences_2;
        private System.Windows.Forms.GroupBox groupBox16;
        private System.Windows.Forms.RadioButton Alternatives_0;
        private System.Windows.Forms.RadioButton Alternatives_1;
        private System.Windows.Forms.RadioButton Alternatives_2;
        private System.Windows.Forms.GroupBox groupBox17;
        private System.Windows.Forms.RadioButton MostRecent_0;
        private System.Windows.Forms.RadioButton MostRecent_2;
        private System.Windows.Forms.RadioButton MostRecent_3;
        private System.Windows.Forms.GroupBox groupBox18;
        private System.Windows.Forms.RadioButton MostLethal_1;
        private System.Windows.Forms.RadioButton MostLethal_0;
        private System.Windows.Forms.RadioButton MostLethal_2;
        private System.Windows.Forms.RadioButton MostLethal_3;
        private System.Windows.Forms.GroupBox groupBox19;
        private System.Windows.Forms.RadioButton MostSerious_0;
        private System.Windows.Forms.RadioButton MostSerious_2;
        private System.Windows.Forms.RadioButton MostSerious_3;
        private System.Windows.Forms.RadioButton MostSerious_1;
        private System.Windows.Forms.RadioButton MostRecent_1;
        private System.Windows.Forms.RadioButton DrugAlcoholUse_10;
        private System.Windows.Forms.RadioButton FamilyAttemptsCompletions_3;
    }
}

