//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using Sante.EMR.SmartClient.Infrastructure.Interface;

using Microsoft.Practices.CompositeUI.SmartParts;
using Sante.EMR.SmartClient.Infrastructure.Module;
using Sante.EMR.SmartClient.Infrastructure.Data.Services;
using Sante.EMR.SmartClient.Infrastructure.Interface.BusinessEntities;

namespace Sante.EMR.SmartClient.Module.OPS
{
    public partial class OPSViewPresenter : CaseQueueViewPresenter
    {
        
        /// <summary>
        /// This method is a placeholder that will be called by the view when it has been loaded.
        /// </summary>
        //public override void OnViewReady()
        //{
        //    base.OnViewReady();
        //}
        
        

        public OPSViewPresenter([ServiceDependency] IDataAccessService dataaccess) : base(dataaccess)
        {
            _db = dataaccess;
            
        }

        /// <summary>
        /// Close the view
        /// </summary>
        public void OnCloseView()
        {
            base.CloseView();
        }

        protected override CaseQueue CreateCaseQueue()
        {
            CaseQueue opsCases = _db.RetrieveCaseQueue(DataAccessType.OPS);

            return opsCases; // base.CreateCaseQueue();
        }

        internal void Search()
        {
            System.Windows.Forms.MessageBox.Show("The method or operation is not implemented.");
        }

        internal void CreateNewCase()
        {
            System.Windows.Forms.MessageBox.Show("The method or operation is not implemented.");
        }

        
    }
}

