//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI.SmartParts;
using Microsoft.Practices.CompositeUI.EventBroker;
using Sante.EMR.SmartClient.Infrastructure.Interface.Constants;
using Sante.EMR.SmartClient.MCT.Services;

namespace Sante.EMR.SmartClient.UCC
{
    public partial class UCCViewPresenter : Presenter<IUCCView>
    {
        IWorkflowStateService _state;
        public UCCViewPresenter([ServiceDependency] IWorkflowStateService workflow)
        {
            _state = workflow;
        }

        /// <summary>
        /// This method is a placeholder that will be called by the view when it has been loaded.
        /// </summary>
        public override void OnViewReady()
        {
            base.OnViewReady();
            _state.Depart = "UCC";
        }

        /// <summary>
        /// Close the view
        /// </summary>
        public void OnCloseView()
        {
            base.CloseView();
        }

        public ISmartPartInfo GetSmartPartInfo(Type smartPartInfoType)
        {
            ISmartPartInfo result =
            (ISmartPartInfo)Activator.CreateInstance(smartPartInfoType);
            result.Title = Properties.Resources.ModuleTitle;//String.Format("Case List #{0}", this._caseQueue.Id);
            result.Description = "Select a UCC form to fill out.";

            return result;

        }

        internal void ShowAssessAndTreatment()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowNewAssessmentTreatment].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowMedicalEval()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowMedicalEval].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowConsentServicesForm()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowNewConsentForServices].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowAuthorizationRelease()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowNewAuthorizationToRelease].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowPrivacyPracticesButton()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowPrivacyPracticesForm].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowAcknowledgementButton()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowAcknowledgementForm].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowHumanRightsForm()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowHumanRightsForm].Fire(View, e, WorkItem, PublicationScope.Global);
        
        }

        internal void ShowLethalityForm()
        {
            EventArgs<string> e = new EventArgs<string>(string.Empty);
            this.WorkItem.EventTopics[EventTopicNames.ShowNewLethalityForm].Fire(View, e, WorkItem, PublicationScope.Global);
        }

        internal void ShowFormWithNoCaseSelection(string s)
        {
            EventArgs<string> e = new EventArgs<string>(s);
            this.WorkItem.EventTopics[s].Fire(View, e, WorkItem, PublicationScope.Global);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="s"></param>
        internal void ShowForm(string s)
        {
            _state.NextForm = s;
            EventArgs<string> e = new EventArgs<string>(s);
            this.WorkItem.EventTopics[EventTopicNames.ShowCaseNumberSelection].Fire(View, e, WorkItem, PublicationScope.Global);
        }
    }
}

