
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.OPS
{
    partial class OPSView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.OPS.OPSViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.SelectFormGroupBox = new System.Windows.Forms.GroupBox();
            this.LethalityButton = new System.Windows.Forms.Button();
            this.IntakeFormButton = new System.Windows.Forms.Button();
            this.OPSTelephoneContact = new System.Windows.Forms.Button();
            this.SelectFormGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // SelectFormGroupBox
            // 
            this.SelectFormGroupBox.Controls.Add(this.OPSTelephoneContact);
            this.SelectFormGroupBox.Controls.Add(this.LethalityButton);
            this.SelectFormGroupBox.Controls.Add(this.IntakeFormButton);
            this.SelectFormGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SelectFormGroupBox.Location = new System.Drawing.Point(0, 0);
            this.SelectFormGroupBox.Name = "SelectFormGroupBox";
            this.SelectFormGroupBox.Size = new System.Drawing.Size(422, 278);
            this.SelectFormGroupBox.TabIndex = 2;
            this.SelectFormGroupBox.TabStop = false;
            this.SelectFormGroupBox.Text = "OPS Forms Menu";
            this.SelectFormGroupBox.Enter += new System.EventHandler(this.SelectFormGroupBox_Enter);
            // 
            // LethalityButton
            // 
            this.LethalityButton.Location = new System.Drawing.Point(127, 82);
            this.LethalityButton.Name = "LethalityButton";
            this.LethalityButton.Size = new System.Drawing.Size(200, 50);
            this.LethalityButton.TabIndex = 6;
            this.LethalityButton.Text = "Lethality Sheet";
            this.LethalityButton.UseVisualStyleBackColor = true;
            this.LethalityButton.Click += new System.EventHandler(this.MCTDispatchButton_Click);
            // 
            // IntakeFormButton
            // 
            this.IntakeFormButton.Location = new System.Drawing.Point(127, 33);
            this.IntakeFormButton.Name = "IntakeFormButton";
            this.IntakeFormButton.Size = new System.Drawing.Size(200, 50);
            this.IntakeFormButton.TabIndex = 5;
            this.IntakeFormButton.Text = "Intake Form";
            this.IntakeFormButton.UseVisualStyleBackColor = true;
            this.IntakeFormButton.Click += new System.EventHandler(this.AssesTreatmentButton_Click);
            // 
            // OPSTelephoneContact
            // 
            this.OPSTelephoneContact.Location = new System.Drawing.Point(127, 131);
            this.OPSTelephoneContact.Name = "OPSTelephoneContact";
            this.OPSTelephoneContact.Size = new System.Drawing.Size(200, 50);
            this.OPSTelephoneContact.TabIndex = 7;
            this.OPSTelephoneContact.Text = "Telephone Contact";
            this.OPSTelephoneContact.UseVisualStyleBackColor = true;
            this.OPSTelephoneContact.Click += new System.EventHandler(this.OPSTelephoneContact_Click);
            // 
            // OPSView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.SelectFormGroupBox);
            this.Name = "OPSView";
            this.Size = new System.Drawing.Size(422, 278);
            this.Load += new System.EventHandler(this.OPSView_Load);
            this.SelectFormGroupBox.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox SelectFormGroupBox;
        private System.Windows.Forms.Button LethalityButton;
        private System.Windows.Forms.Button IntakeFormButton;
        private System.Windows.Forms.Button OPSTelephoneContact;
    }
}

