//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------
using System;

namespace Sante.EMR.SmartClient.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames
    {
        /// <summary>
        /// Event fired to tell the shell to update the status panel
        /// </summary>
        /// 
        public const string ShowInformedMedicalConsent = "ShowInformedMedicalConsent";
        public const string ShowIntakeForm = "ShowNewIntakeForm";
        public const string ShowIntakeFormPG = "ShowNewIntakeFormPG";
        public const string ShowIntakeFormES = "ShowNewIntakeFormES";

        public const string SerializeOutbox = "SerializeOutbox";
        public const string StatusUpdate = "StatusUpdate";
        public const string Kill = "Kill";
        public const string OnStartUp = "OnStartUp";
        public const string LongProcess = "LongProcess";
        public const string Add = "Add";
        public const string SaveForm = "SaveForm";
        public const string SaveFormEvent = "SaveFormEvent";
        public const string SaveCaseEvent = "SaveCaseEvent";
        public const string SaveLethalityForm = "SaveLethalityForm";
        public const string NewCase = "NewCase";
        public const string ShowNewAssessmentTreatment = "ShowNewAssessmentTreatmentForm";
        public const string ShowNewAssessmentTreatmentUCC = "ShowNewAssessmentTreatmentUCCForm";
        public const string ShowNewLethalityForm = "ShowNewLethalityForm";
        public const string ShowNewConsentForServices = "ShowNewConsentForServices";
        public const string ShowNewAuthorizationToRelease = "ShowNewAuthorizationToRelease";
        public const string ShowHumanRightsForm = "ShowHumanRightsForm";
        public const string ShowAcknowledgementForm = "ShowAcknowledgementForm";
        public const string ShowPrivacyPracticesForm = "ShowPrivacyPracticesForm";
        public const string ShowMedicalEval = "ShowMedicalEval";
        public const string ShowNotesForm = "ShowNotesForm";
        public const string ShowInformedConsentForm = "ShowInformedConsentForm";
        public const string SuccessfulSentForm = "SuccessfulSentForm";
        public const string ConsentForServicesWorkFlow = "ConsentForServicesWorkFlow";
        public const string ShowCaseNumberSelection = "ShowCaseNumberSelection";
        public const string ShowTelephoneContact = "ShowTelephoneContact";
        public const string ShowOPSTelephoneContact = "ShowOPSTelephoneContact";
        public const string ShowIndividualTreatmentForm = "ShowIndividualTreatmentForm";
        public const string ShowNewMCTDispatch = "ShowNewMCTDispatch";
        public const string ShowNewMCTDispatchES = "ShowNewMCTDispatchES";
        public const string ShowNewMCTDispatchAA = "ShowNewMCTDispatchAA";
        public const string ShowNewMCTDispatchPG = "ShowNewMCTDispatchPG";
                
    }
}
