
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using Sante.EMR.SmartClient.Infrastructure.Module;
using System.Windows.Forms;
namespace Sante.EMR.SmartClient.Module.MCT
{
    partial class MCTView : CaseQueueView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        //private Sante.EMR.SmartClient.Module.MCT.MCTViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.UploadSignatureButton = new ToolStripButton();
            BottomToolStrip = new ToolStrip();
            // 
            // UploadSignatureButton
            // 
            this.UploadSignatureButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.UploadSignatureButton.Name = "UploadSignatureButton";
            this.UploadSignatureButton.Size = new System.Drawing.Size(60, 22);
            this.UploadSignatureButton.Text = "Upload Signatures";
            this.UploadSignatureButton.Click += new System.EventHandler(UploadSignatureButton_Click);
            
            components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;

            // 
            // toolStrip1
            // 
            this.BottomToolStrip.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.BottomToolStrip.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden;
            this.BottomToolStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.UploadSignatureButton,
            this.NewCaseButton,
            this.SearchButton});
            this.BottomToolStrip.Location = new System.Drawing.Point(0, 253);
            this.BottomToolStrip.Name = "toolStrip1";
            this.BottomToolStrip.RenderMode = System.Windows.Forms.ToolStripRenderMode.System;
            this.BottomToolStrip.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.BottomToolStrip.Size = new System.Drawing.Size(422, 25);
            this.BottomToolStrip.TabIndex = 7;
            this.BottomToolStrip.Text = "toolStrip1";

            Controls.Add(BottomToolStrip);


        }

        void UploadSignatureButton_Click(object sender, System.EventArgs e)
        {
            MessageBox.Show("The method or operation is not implemented.");
        }
        protected ToolStripButton UploadSignatureButton;
        
        protected ToolStrip BottomToolStrip;

        #endregion
    }
}

