
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.CISM
{
    partial class CISMView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.CISM.CISMViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.ConsentServicesButton = new System.Windows.Forms.Button();
            this.SelectFormGroupBox = new System.Windows.Forms.GroupBox();
            this.MCTDispatchButton = new System.Windows.Forms.Button();
            this.AssesTreatmentButton = new System.Windows.Forms.Button();
            this.SelectFormGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // ConsentServicesButton
            // 
            this.ConsentServicesButton.Location = new System.Drawing.Point(127, 132);
            this.ConsentServicesButton.Name = "ConsentServicesButton";
            this.ConsentServicesButton.Size = new System.Drawing.Size(200, 50);
            this.ConsentServicesButton.TabIndex = 7;
            this.ConsentServicesButton.Text = "Discharge";
            this.ConsentServicesButton.UseVisualStyleBackColor = true;
            // 
            // SelectFormGroupBox
            // 
            this.SelectFormGroupBox.Controls.Add(this.ConsentServicesButton);
            this.SelectFormGroupBox.Controls.Add(this.MCTDispatchButton);
            this.SelectFormGroupBox.Controls.Add(this.AssesTreatmentButton);
            this.SelectFormGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SelectFormGroupBox.Location = new System.Drawing.Point(0, 0);
            this.SelectFormGroupBox.Name = "SelectFormGroupBox";
            this.SelectFormGroupBox.Size = new System.Drawing.Size(500, 278);
            this.SelectFormGroupBox.TabIndex = 1;
            this.SelectFormGroupBox.TabStop = false;
            this.SelectFormGroupBox.Text = "CISM Forms Menu";
            // 
            // MCTDispatchButton
            // 
            this.MCTDispatchButton.Location = new System.Drawing.Point(127, 82);
            this.MCTDispatchButton.Name = "MCTDispatchButton";
            this.MCTDispatchButton.Size = new System.Drawing.Size(200, 50);
            this.MCTDispatchButton.TabIndex = 6;
            this.MCTDispatchButton.Text = "Telephone Contact";
            this.MCTDispatchButton.UseVisualStyleBackColor = true;
            // 
            // AssesTreatmentButton
            // 
            this.AssesTreatmentButton.Location = new System.Drawing.Point(127, 33);
            this.AssesTreatmentButton.Name = "AssesTreatmentButton";
            this.AssesTreatmentButton.Size = new System.Drawing.Size(200, 50);
            this.AssesTreatmentButton.TabIndex = 5;
            this.AssesTreatmentButton.Text = "CISM Intervention";
            this.AssesTreatmentButton.UseVisualStyleBackColor = true;
            // 
            // CISMView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.SelectFormGroupBox);
            this.Name = "CISMView";
            this.Size = new System.Drawing.Size(500, 278);
            this.Load += new System.EventHandler(this.CISMView_Load);
            this.SelectFormGroupBox.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button ConsentServicesButton;
        private System.Windows.Forms.GroupBox SelectFormGroupBox;
        private System.Windows.Forms.Button MCTDispatchButton;
        private System.Windows.Forms.Button AssesTreatmentButton;
    }
}

