
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Sante.EMR.SmartClient.MCT
{
    partial class MCTDispatchView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Sante.EMR.SmartClient.MCT.MCTDispatchViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MCTDispatchView));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.SaveToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.Section1TabPage = new System.Windows.Forms.TabPage();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.Enviromental = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.Additional = new System.Windows.Forms.TextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.Information = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.OthersInvolved = new System.Windows.Forms.TextBox();
            this.Precinct = new System.Windows.Forms.ComboBox();
            this.label11 = new System.Windows.Forms.Label();
            this.location = new System.Windows.Forms.ComboBox();
            this.label10 = new System.Windows.Forms.Label();
            this.DispatchedGroupBox = new System.Windows.Forms.GroupBox();
            this.dispatch_followup = new System.Windows.Forms.RadioButton();
            this.dispatch_new = new System.Windows.Forms.RadioButton();
            this.ClientInfoGroupBox = new System.Windows.Forms.GroupBox();
            this.groupBox10 = new System.Windows.Forms.GroupBox();
            this.DivertedJail_na = new System.Windows.Forms.RadioButton();
            this.DivertedJail_no = new System.Windows.Forms.RadioButton();
            this.DivertedJail_yes = new System.Windows.Forms.RadioButton();
            this.groupBox9 = new System.Windows.Forms.GroupBox();
            this.DivertedER_na = new System.Windows.Forms.RadioButton();
            this.DivertedER_no = new System.Windows.Forms.RadioButton();
            this.DivertedER_yes = new System.Windows.Forms.RadioButton();
            this.EndTime = new System.Windows.Forms.DateTimePicker();
            this.label23 = new System.Windows.Forms.Label();
            this.EndDate = new System.Windows.Forms.DateTimePicker();
            this.label22 = new System.Windows.Forms.Label();
            this.ArrivalDate = new System.Windows.Forms.DateTimePicker();
            this.label21 = new System.Windows.Forms.Label();
            this.DispatchDate = new System.Windows.Forms.DateTimePicker();
            this.label20 = new System.Windows.Forms.Label();
            this.TotalTime = new System.Windows.Forms.TextBox();
            this.DispatchedBy = new System.Windows.Forms.ComboBox();
            this.label14 = new System.Windows.Forms.Label();
            this.Time = new System.Windows.Forms.TextBox();
            this.Date = new System.Windows.Forms.TextBox();
            this.Mileage = new System.Windows.Forms.NumericUpDown();
            this.ArrivalTime = new System.Windows.Forms.DateTimePicker();
            this.DispatchTime = new System.Windows.Forms.DateTimePicker();
            this.UserName = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.CaseNumber = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.Team = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.CaseNumberlabel = new System.Windows.Forms.Label();
            this.Section2TabPage = new System.Windows.Forms.TabPage();
            this.groupBox8 = new System.Windows.Forms.GroupBox();
            this.Treatment = new System.Windows.Forms.CheckedListBox();
            this.label13 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.Outcome = new System.Windows.Forms.CheckedListBox();
            this.label7 = new System.Windows.Forms.Label();
            this.OtherOutcomeDet = new System.Windows.Forms.TextBox();
            this.Diagnostic = new System.Windows.Forms.ComboBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.label8 = new System.Windows.Forms.Label();
            this.FocalIssues = new System.Windows.Forms.CheckedListBox();
            this.OtherDesc = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.Interventions = new System.Windows.Forms.CheckedListBox();
            this.OtherDesclbl = new System.Windows.Forms.Label();
            this.Other = new System.Windows.Forms.TextBox();
            this.toolStrip1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.Section1TabPage.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.DispatchedGroupBox.SuspendLayout();
            this.ClientInfoGroupBox.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox9.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Mileage)).BeginInit();
            this.Section2TabPage.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.SaveToolStripButton});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(630, 25);
            this.toolStrip1.TabIndex = 1;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // SaveToolStripButton
            // 
            this.SaveToolStripButton.Image = ((System.Drawing.Image)(resources.GetObject("SaveToolStripButton.Image")));
            this.SaveToolStripButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.SaveToolStripButton.Name = "SaveToolStripButton";
            this.SaveToolStripButton.Size = new System.Drawing.Size(51, 22);
            this.SaveToolStripButton.Text = "Save";
            this.SaveToolStripButton.Click += new System.EventHandler(this.SaveToolStripButton_Click);
            // 
            // tabControl1
            // 
            this.tabControl1.Appearance = System.Windows.Forms.TabAppearance.FlatButtons;
            this.tabControl1.Controls.Add(this.Section1TabPage);
            this.tabControl1.Controls.Add(this.Section2TabPage);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 25);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(630, 615);
            this.tabControl1.TabIndex = 2;
            // 
            // Section1TabPage
            // 
            this.Section1TabPage.Controls.Add(this.groupBox6);
            this.Section1TabPage.Controls.Add(this.groupBox3);
            this.Section1TabPage.Controls.Add(this.groupBox2);
            this.Section1TabPage.Controls.Add(this.groupBox1);
            this.Section1TabPage.Controls.Add(this.Precinct);
            this.Section1TabPage.Controls.Add(this.label11);
            this.Section1TabPage.Controls.Add(this.location);
            this.Section1TabPage.Controls.Add(this.label10);
            this.Section1TabPage.Controls.Add(this.DispatchedGroupBox);
            this.Section1TabPage.Controls.Add(this.ClientInfoGroupBox);
            this.Section1TabPage.Location = new System.Drawing.Point(4, 25);
            this.Section1TabPage.Name = "Section1TabPage";
            this.Section1TabPage.Padding = new System.Windows.Forms.Padding(3);
            this.Section1TabPage.Size = new System.Drawing.Size(622, 586);
            this.Section1TabPage.TabIndex = 0;
            this.Section1TabPage.Text = "Section 1";
            this.Section1TabPage.UseVisualStyleBackColor = true;
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.Enviromental);
            this.groupBox6.Location = new System.Drawing.Point(-1, 412);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(624, 81);
            this.groupBox6.TabIndex = 40;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Environmental Assessment";
            // 
            // Enviromental
            // 
            this.Enviromental.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Enviromental.Location = new System.Drawing.Point(3, 16);
            this.Enviromental.Multiline = true;
            this.Enviromental.Name = "Enviromental";
            this.Enviromental.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Enviromental.Size = new System.Drawing.Size(618, 62);
            this.Enviromental.TabIndex = 0;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.Additional);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.groupBox3.Location = new System.Drawing.Point(3, 499);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(616, 84);
            this.groupBox3.TabIndex = 39;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Additional Information Obtained During Visit";
            // 
            // Additional
            // 
            this.Additional.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Additional.Location = new System.Drawing.Point(3, 16);
            this.Additional.Multiline = true;
            this.Additional.Name = "Additional";
            this.Additional.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Additional.Size = new System.Drawing.Size(610, 65);
            this.Additional.TabIndex = 0;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.Information);
            this.groupBox2.Location = new System.Drawing.Point(-1, 330);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(624, 81);
            this.groupBox2.TabIndex = 38;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Information Necessary for Locating Client";
            // 
            // Information
            // 
            this.Information.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Information.Location = new System.Drawing.Point(3, 16);
            this.Information.Multiline = true;
            this.Information.Name = "Information";
            this.Information.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Information.Size = new System.Drawing.Size(618, 62);
            this.Information.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.OthersInvolved);
            this.groupBox1.Location = new System.Drawing.Point(-1, 248);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(624, 81);
            this.groupBox1.TabIndex = 37;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Others Involved In Dispatch";
            // 
            // OthersInvolved
            // 
            this.OthersInvolved.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OthersInvolved.Location = new System.Drawing.Point(3, 16);
            this.OthersInvolved.Multiline = true;
            this.OthersInvolved.Name = "OthersInvolved";
            this.OthersInvolved.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.OthersInvolved.Size = new System.Drawing.Size(618, 62);
            this.OthersInvolved.TabIndex = 0;
            // 
            // Precinct
            // 
            this.Precinct.FormattingEnabled = true;
            this.Precinct.Items.AddRange(new object[] {
            "1",
            "2",
            "3",
            "4",
            "6",
            "7",
            "8",
            "9",
            "11",
            "12",
            "Other"});
            this.Precinct.Location = new System.Drawing.Point(469, 220);
            this.Precinct.Name = "Precinct";
            this.Precinct.Size = new System.Drawing.Size(74, 21);
            this.Precinct.TabIndex = 14;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(418, 223);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(49, 13);
            this.label11.TabIndex = 35;
            this.label11.Text = "Precinct:";
            // 
            // location
            // 
            this.location.FormattingEnabled = true;
            this.location.Items.AddRange(new object[] {
            "Residence",
            "Office",
            "School",
            "Provider",
            "Court/Jail",
            "Workplace",
            "Hospital",
            "Other"});
            this.location.Location = new System.Drawing.Point(317, 220);
            this.location.Name = "location";
            this.location.Size = new System.Drawing.Size(98, 21);
            this.location.TabIndex = 13;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(236, 225);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(83, 13);
            this.label10.TabIndex = 33;
            this.label10.Text = "Location of Call:";
            // 
            // DispatchedGroupBox
            // 
            this.DispatchedGroupBox.Controls.Add(this.dispatch_followup);
            this.DispatchedGroupBox.Controls.Add(this.dispatch_new);
            this.DispatchedGroupBox.Location = new System.Drawing.Point(6, 205);
            this.DispatchedGroupBox.Name = "DispatchedGroupBox";
            this.DispatchedGroupBox.Size = new System.Drawing.Size(214, 37);
            this.DispatchedGroupBox.TabIndex = 12;
            this.DispatchedGroupBox.TabStop = false;
            this.DispatchedGroupBox.Text = "Dispatched";
            // 
            // dispatch_followup
            // 
            this.dispatch_followup.AutoSize = true;
            this.dispatch_followup.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dispatch_followup.Location = new System.Drawing.Point(75, 14);
            this.dispatch_followup.Name = "dispatch_followup";
            this.dispatch_followup.Size = new System.Drawing.Size(106, 16);
            this.dispatch_followup.TabIndex = 1;
            this.dispatch_followup.TabStop = true;
            this.dispatch_followup.Text = "Previous/Follow-Up";
            this.dispatch_followup.UseVisualStyleBackColor = true;
            // 
            // dispatch_new
            // 
            this.dispatch_new.AutoSize = true;
            this.dispatch_new.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dispatch_new.Location = new System.Drawing.Point(25, 14);
            this.dispatch_new.Name = "dispatch_new";
            this.dispatch_new.Size = new System.Drawing.Size(43, 16);
            this.dispatch_new.TabIndex = 0;
            this.dispatch_new.TabStop = true;
            this.dispatch_new.Text = "New";
            this.dispatch_new.UseVisualStyleBackColor = true;
            // 
            // ClientInfoGroupBox
            // 
            this.ClientInfoGroupBox.Controls.Add(this.groupBox10);
            this.ClientInfoGroupBox.Controls.Add(this.groupBox9);
            this.ClientInfoGroupBox.Controls.Add(this.EndTime);
            this.ClientInfoGroupBox.Controls.Add(this.label23);
            this.ClientInfoGroupBox.Controls.Add(this.EndDate);
            this.ClientInfoGroupBox.Controls.Add(this.label22);
            this.ClientInfoGroupBox.Controls.Add(this.ArrivalDate);
            this.ClientInfoGroupBox.Controls.Add(this.label21);
            this.ClientInfoGroupBox.Controls.Add(this.DispatchDate);
            this.ClientInfoGroupBox.Controls.Add(this.label20);
            this.ClientInfoGroupBox.Controls.Add(this.TotalTime);
            this.ClientInfoGroupBox.Controls.Add(this.DispatchedBy);
            this.ClientInfoGroupBox.Controls.Add(this.label14);
            this.ClientInfoGroupBox.Controls.Add(this.Time);
            this.ClientInfoGroupBox.Controls.Add(this.Date);
            this.ClientInfoGroupBox.Controls.Add(this.Mileage);
            this.ClientInfoGroupBox.Controls.Add(this.ArrivalTime);
            this.ClientInfoGroupBox.Controls.Add(this.DispatchTime);
            this.ClientInfoGroupBox.Controls.Add(this.UserName);
            this.ClientInfoGroupBox.Controls.Add(this.label12);
            this.ClientInfoGroupBox.Controls.Add(this.label9);
            this.ClientInfoGroupBox.Controls.Add(this.CaseNumber);
            this.ClientInfoGroupBox.Controls.Add(this.label6);
            this.ClientInfoGroupBox.Controls.Add(this.label4);
            this.ClientInfoGroupBox.Controls.Add(this.label5);
            this.ClientInfoGroupBox.Controls.Add(this.Team);
            this.ClientInfoGroupBox.Controls.Add(this.label3);
            this.ClientInfoGroupBox.Controls.Add(this.label2);
            this.ClientInfoGroupBox.Controls.Add(this.label1);
            this.ClientInfoGroupBox.Controls.Add(this.CaseNumberlabel);
            this.ClientInfoGroupBox.Dock = System.Windows.Forms.DockStyle.Top;
            this.ClientInfoGroupBox.Location = new System.Drawing.Point(3, 3);
            this.ClientInfoGroupBox.Name = "ClientInfoGroupBox";
            this.ClientInfoGroupBox.Size = new System.Drawing.Size(616, 190);
            this.ClientInfoGroupBox.TabIndex = 31;
            this.ClientInfoGroupBox.TabStop = false;
            this.ClientInfoGroupBox.Text = "Administrative";
            // 
            // groupBox10
            // 
            this.groupBox10.Controls.Add(this.DivertedJail_na);
            this.groupBox10.Controls.Add(this.DivertedJail_no);
            this.groupBox10.Controls.Add(this.DivertedJail_yes);
            this.groupBox10.Location = new System.Drawing.Point(425, 51);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new System.Drawing.Size(158, 43);
            this.groupBox10.TabIndex = 47;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "Diverted from Jail:";
            // 
            // DivertedJail_na
            // 
            this.DivertedJail_na.AutoSize = true;
            this.DivertedJail_na.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedJail_na.Location = new System.Drawing.Point(91, 19);
            this.DivertedJail_na.Name = "DivertedJail_na";
            this.DivertedJail_na.Size = new System.Drawing.Size(40, 16);
            this.DivertedJail_na.TabIndex = 46;
            this.DivertedJail_na.TabStop = true;
            this.DivertedJail_na.Text = "N/A";
            this.DivertedJail_na.UseVisualStyleBackColor = true;
            // 
            // DivertedJail_no
            // 
            this.DivertedJail_no.AutoSize = true;
            this.DivertedJail_no.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedJail_no.Location = new System.Drawing.Point(50, 19);
            this.DivertedJail_no.Name = "DivertedJail_no";
            this.DivertedJail_no.Size = new System.Drawing.Size(35, 16);
            this.DivertedJail_no.TabIndex = 45;
            this.DivertedJail_no.TabStop = true;
            this.DivertedJail_no.Text = "No";
            this.DivertedJail_no.UseVisualStyleBackColor = true;
            // 
            // DivertedJail_yes
            // 
            this.DivertedJail_yes.AutoSize = true;
            this.DivertedJail_yes.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedJail_yes.Location = new System.Drawing.Point(6, 19);
            this.DivertedJail_yes.Name = "DivertedJail_yes";
            this.DivertedJail_yes.Size = new System.Drawing.Size(38, 16);
            this.DivertedJail_yes.TabIndex = 44;
            this.DivertedJail_yes.TabStop = true;
            this.DivertedJail_yes.Text = "Yes";
            this.DivertedJail_yes.UseVisualStyleBackColor = true;
            // 
            // groupBox9
            // 
            this.groupBox9.Controls.Add(this.DivertedER_na);
            this.groupBox9.Controls.Add(this.DivertedER_no);
            this.groupBox9.Controls.Add(this.DivertedER_yes);
            this.groupBox9.Location = new System.Drawing.Point(427, 100);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new System.Drawing.Size(156, 43);
            this.groupBox9.TabIndex = 45;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Diverted from Incarceration:";
            // 
            // DivertedER_na
            // 
            this.DivertedER_na.AutoSize = true;
            this.DivertedER_na.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedER_na.Location = new System.Drawing.Point(91, 19);
            this.DivertedER_na.Name = "DivertedER_na";
            this.DivertedER_na.Size = new System.Drawing.Size(40, 16);
            this.DivertedER_na.TabIndex = 46;
            this.DivertedER_na.TabStop = true;
            this.DivertedER_na.Text = "N/A";
            this.DivertedER_na.UseVisualStyleBackColor = true;
            // 
            // DivertedER_no
            // 
            this.DivertedER_no.AutoSize = true;
            this.DivertedER_no.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedER_no.Location = new System.Drawing.Point(50, 19);
            this.DivertedER_no.Name = "DivertedER_no";
            this.DivertedER_no.Size = new System.Drawing.Size(35, 16);
            this.DivertedER_no.TabIndex = 45;
            this.DivertedER_no.TabStop = true;
            this.DivertedER_no.Text = "No";
            this.DivertedER_no.UseVisualStyleBackColor = true;
            // 
            // DivertedER_yes
            // 
            this.DivertedER_yes.AutoSize = true;
            this.DivertedER_yes.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F);
            this.DivertedER_yes.Location = new System.Drawing.Point(6, 19);
            this.DivertedER_yes.Name = "DivertedER_yes";
            this.DivertedER_yes.Size = new System.Drawing.Size(38, 16);
            this.DivertedER_yes.TabIndex = 44;
            this.DivertedER_yes.TabStop = true;
            this.DivertedER_yes.Text = "Yes";
            this.DivertedER_yes.UseVisualStyleBackColor = true;
            // 
            // EndTime
            // 
            this.EndTime.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.EndTime.Location = new System.Drawing.Point(284, 159);
            this.EndTime.Name = "EndTime";
            this.EndTime.ShowUpDown = true;
            this.EndTime.Size = new System.Drawing.Size(100, 20);
            this.EndTime.TabIndex = 42;
            // 
            // label23
            // 
            this.label23.AutoSize = true;
            this.label23.Location = new System.Drawing.Point(226, 164);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(55, 13);
            this.label23.TabIndex = 41;
            this.label23.Text = "End Time:";
            // 
            // EndDate
            // 
            this.EndDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.EndDate.Location = new System.Drawing.Point(92, 159);
            this.EndDate.Name = "EndDate";
            this.EndDate.Size = new System.Drawing.Size(100, 20);
            this.EndDate.TabIndex = 39;
            // 
            // label22
            // 
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(29, 161);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(55, 13);
            this.label22.TabIndex = 40;
            this.label22.Text = "End Date:";
            // 
            // ArrivalDate
            // 
            this.ArrivalDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.ArrivalDate.Location = new System.Drawing.Point(92, 73);
            this.ArrivalDate.Name = "ArrivalDate";
            this.ArrivalDate.Size = new System.Drawing.Size(97, 20);
            this.ArrivalDate.TabIndex = 38;
            this.ArrivalDate.ValueChanged += new System.EventHandler(this.ArrivalDate_ValueChanged);
            // 
            // label21
            // 
            this.label21.AutoSize = true;
            this.label21.Location = new System.Drawing.Point(20, 78);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(65, 13);
            this.label21.TabIndex = 37;
            this.label21.Text = "Arrival Date:";
            // 
            // DispatchDate
            // 
            this.DispatchDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.DispatchDate.Location = new System.Drawing.Point(284, 21);
            this.DispatchDate.Name = "DispatchDate";
            this.DispatchDate.Size = new System.Drawing.Size(100, 20);
            this.DispatchDate.TabIndex = 35;
            this.DispatchDate.ValueChanged += new System.EventHandler(this.DispatchDate_ValueChanged);
            // 
            // label20
            // 
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(203, 23);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(78, 13);
            this.label20.TabIndex = 36;
            this.label20.Text = "Dispatch Date:";
            // 
            // TotalTime
            // 
            this.TotalTime.Location = new System.Drawing.Point(284, 76);
            this.TotalTime.Name = "TotalTime";
            this.TotalTime.Size = new System.Drawing.Size(100, 20);
            this.TotalTime.TabIndex = 34;
            // 
            // DispatchedBy
            // 
            this.DispatchedBy.FormattingEnabled = true;
            this.DispatchedBy.Items.AddRange(new object[] {
            "MCT",
            "IHIT",
            "911 Dispatched",
            "OPS",
            "Police PCT",
            "Fire"});
            this.DispatchedBy.Location = new System.Drawing.Point(284, 129);
            this.DispatchedBy.Name = "DispatchedBy";
            this.DispatchedBy.Size = new System.Drawing.Size(100, 21);
            this.DispatchedBy.TabIndex = 31;
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(202, 134);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(79, 13);
            this.label14.TabIndex = 30;
            this.label14.Text = "Dispatched By:";
            // 
            // Time
            // 
            this.Time.Location = new System.Drawing.Point(91, 47);
            this.Time.Name = "Time";
            this.Time.ReadOnly = true;
            this.Time.Size = new System.Drawing.Size(100, 20);
            this.Time.TabIndex = 29;
            // 
            // Date
            // 
            this.Date.Location = new System.Drawing.Point(92, 19);
            this.Date.Name = "Date";
            this.Date.ReadOnly = true;
            this.Date.Size = new System.Drawing.Size(100, 20);
            this.Date.TabIndex = 28;
            // 
            // Mileage
            // 
            this.Mileage.Location = new System.Drawing.Point(495, 159);
            this.Mileage.Name = "Mileage";
            this.Mileage.Size = new System.Drawing.Size(47, 20);
            this.Mileage.TabIndex = 27;
            // 
            // ArrivalTime
            // 
            this.ArrivalTime.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.ArrivalTime.Location = new System.Drawing.Point(92, 103);
            this.ArrivalTime.Name = "ArrivalTime";
            this.ArrivalTime.ShowUpDown = true;
            this.ArrivalTime.Size = new System.Drawing.Size(99, 20);
            this.ArrivalTime.TabIndex = 7;
            this.ArrivalTime.ValueChanged += new System.EventHandler(this.ArrivalTime_ValueChanged);
            // 
            // DispatchTime
            // 
            this.DispatchTime.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.DispatchTime.Location = new System.Drawing.Point(284, 49);
            this.DispatchTime.Name = "DispatchTime";
            this.DispatchTime.ShowUpDown = true;
            this.DispatchTime.Size = new System.Drawing.Size(100, 20);
            this.DispatchTime.TabIndex = 2;
            this.DispatchTime.ValueChanged += new System.EventHandler(this.DispatchTime_ValueChanged);
            // 
            // UserName
            // 
            this.UserName.Location = new System.Drawing.Point(284, 103);
            this.UserName.Name = "UserName";
            this.UserName.Size = new System.Drawing.Size(100, 20);
            this.UserName.TabIndex = 8;
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(225, 105);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(58, 13);
            this.label12.TabIndex = 23;
            this.label12.Text = "Username:";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(445, 164);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(47, 13);
            this.label9.TabIndex = 21;
            this.label9.Text = "Mileage:";
            // 
            // CaseNumber
            // 
            this.CaseNumber.Location = new System.Drawing.Point(501, 21);
            this.CaseNumber.Name = "CaseNumber";
            this.CaseNumber.Size = new System.Drawing.Size(100, 20);
            this.CaseNumber.TabIndex = 3;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(424, 24);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(74, 13);
            this.label6.TabIndex = 15;
            this.label6.Text = "Case Number:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(221, 77);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(60, 13);
            this.label4.TabIndex = 12;
            this.label4.Text = "Total Time:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(203, 51);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(78, 13);
            this.label5.TabIndex = 11;
            this.label5.Text = "Dispatch Time:";
            // 
            // Team
            // 
            this.Team.Location = new System.Drawing.Point(92, 129);
            this.Team.Name = "Team";
            this.Team.Size = new System.Drawing.Size(100, 20);
            this.Team.TabIndex = 10;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 132);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(83, 13);
            this.label3.TabIndex = 9;
            this.label3.Text = "Team Members:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(19, 103);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(65, 13);
            this.label2.TabIndex = 2;
            this.label2.Text = "Arrival Time:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(51, 48);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(33, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Time:";
            // 
            // CaseNumberlabel
            // 
            this.CaseNumberlabel.AutoSize = true;
            this.CaseNumberlabel.Location = new System.Drawing.Point(51, 22);
            this.CaseNumberlabel.Name = "CaseNumberlabel";
            this.CaseNumberlabel.Size = new System.Drawing.Size(33, 13);
            this.CaseNumberlabel.TabIndex = 0;
            this.CaseNumberlabel.Text = "Date:";
            // 
            // Section2TabPage
            // 
            this.Section2TabPage.Controls.Add(this.groupBox8);
            this.Section2TabPage.Controls.Add(this.label13);
            this.Section2TabPage.Controls.Add(this.groupBox7);
            this.Section2TabPage.Controls.Add(this.Diagnostic);
            this.Section2TabPage.Controls.Add(this.groupBox5);
            this.Section2TabPage.Controls.Add(this.groupBox4);
            this.Section2TabPage.Location = new System.Drawing.Point(4, 25);
            this.Section2TabPage.Name = "Section2TabPage";
            this.Section2TabPage.Padding = new System.Windows.Forms.Padding(3);
            this.Section2TabPage.Size = new System.Drawing.Size(622, 586);
            this.Section2TabPage.TabIndex = 1;
            this.Section2TabPage.Text = "Section 2";
            this.Section2TabPage.UseVisualStyleBackColor = true;
            // 
            // groupBox8
            // 
            this.groupBox8.Controls.Add(this.Treatment);
            this.groupBox8.Location = new System.Drawing.Point(3, 3);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new System.Drawing.Size(616, 42);
            this.groupBox8.TabIndex = 3;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "Treatment";
            // 
            // Treatment
            // 
            this.Treatment.FormattingEnabled = true;
            this.Treatment.Items.AddRange(new object[] {
            "Client was intoxicated upon arrival",
            "Client in treatment currently in the community"});
            this.Treatment.Location = new System.Drawing.Point(7, 16);
            this.Treatment.MultiColumn = true;
            this.Treatment.Name = "Treatment";
            this.Treatment.Size = new System.Drawing.Size(250, 19);
            this.Treatment.TabIndex = 48;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(12, 533);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(102, 13);
            this.label13.TabIndex = 49;
            this.label13.Text = "Diagnostic Category";
            // 
            // groupBox7
            // 
            this.groupBox7.Controls.Add(this.Outcome);
            this.groupBox7.Controls.Add(this.label7);
            this.groupBox7.Controls.Add(this.OtherOutcomeDet);
            this.groupBox7.Location = new System.Drawing.Point(3, 260);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(616, 71);
            this.groupBox7.TabIndex = 2;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Outcome";
            // 
            // Outcome
            // 
            this.Outcome.FormattingEnabled = true;
            this.Outcome.Items.AddRange(new object[] {
            "Stable",
            "Stable with support",
            "Deteriorating Sx",
            "With Police",
            "At Risk for Safety",
            "In ER",
            "Other"});
            this.Outcome.Location = new System.Drawing.Point(7, 16);
            this.Outcome.MultiColumn = true;
            this.Outcome.Name = "Outcome";
            this.Outcome.Size = new System.Drawing.Size(364, 49);
            this.Outcome.TabIndex = 52;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(378, 45);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(31, 12);
            this.label7.TabIndex = 51;
            this.label7.Text = "Other:";
            // 
            // OtherOutcomeDet
            // 
            this.OtherOutcomeDet.Location = new System.Drawing.Point(421, 41);
            this.OtherOutcomeDet.Name = "OtherOutcomeDet";
            this.OtherOutcomeDet.Size = new System.Drawing.Size(143, 20);
            this.OtherOutcomeDet.TabIndex = 50;
            // 
            // Diagnostic
            // 
            this.Diagnostic.FormattingEnabled = true;
            this.Diagnostic.Items.AddRange(new object[] {
            "Mood Disorder",
            "Mental Retardation",
            "Cognitive Disorder ",
            "Child/ Adol Disorder",
            "Dx due to medical condition",
            "Dissociative Disorder",
            "Eating Disorder",
            "Clients in Treatment",
            "Substance Disorders",
            "Anxiety",
            "Psychotic/ Thought Disorder",
            "Personality Disorder",
            "Undetermined",
            "Not Applicable",
            "Other"});
            this.Diagnostic.Location = new System.Drawing.Point(120, 530);
            this.Diagnostic.Name = "Diagnostic";
            this.Diagnostic.Size = new System.Drawing.Size(121, 21);
            this.Diagnostic.TabIndex = 48;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.label8);
            this.groupBox5.Controls.Add(this.FocalIssues);
            this.groupBox5.Controls.Add(this.OtherDesc);
            this.groupBox5.Location = new System.Drawing.Point(5, 334);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(613, 175);
            this.groupBox5.TabIndex = 1;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Focal Issue";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(6, 142);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(31, 12);
            this.label8.TabIndex = 58;
            this.label8.Text = "Other:";
            // 
            // FocalIssues
            // 
            this.FocalIssues.FormattingEnabled = true;
            this.FocalIssues.Items.AddRange(new object[] {
            "Homicide/Violence",
            "Sexual Assault",
            "Family Conflict with Child/Adol",
            "Chronic MI",
            "Situational Crisis",
            "Death Other Than Suicide",
            "Suicide Attempt",
            "Depression",
            "Marital/ Significant Other Conflict",
            "Emergency Petition",
            "Anxiety",
            "Suicide Ideation",
            "Substance Abuse",
            "Domestic Violence",
            "Medical Issue Primary",
            "Financial",
            "Death by Suicide",
            "Child with Significant Illness",
            "Child Abuse (Physical/Sexual/Neglect)",
            "Elderly with Confusion, dementia",
            "Community Resources",
            "Fatal Accident",
            "Child/Adol Behavior",
            "Runaway",
            "Homeless/Major Financial",
            "Other"});
            this.FocalIssues.Location = new System.Drawing.Point(6, 19);
            this.FocalIssues.MultiColumn = true;
            this.FocalIssues.Name = "FocalIssues";
            this.FocalIssues.Size = new System.Drawing.Size(600, 109);
            this.FocalIssues.TabIndex = 44;
            // 
            // OtherDesc
            // 
            this.OtherDesc.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OtherDesc.Location = new System.Drawing.Point(43, 139);
            this.OtherDesc.Name = "OtherDesc";
            this.OtherDesc.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.OtherDesc.Size = new System.Drawing.Size(104, 18);
            this.OtherDesc.TabIndex = 57;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.Interventions);
            this.groupBox4.Controls.Add(this.OtherDesclbl);
            this.groupBox4.Controls.Add(this.Other);
            this.groupBox4.Location = new System.Drawing.Point(3, 44);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(616, 208);
            this.groupBox4.TabIndex = 0;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Interventions Used";
            // 
            // Interventions
            // 
            this.Interventions.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Interventions.FormattingEnabled = true;
            this.Interventions.Items.AddRange(new object[] {
            "Jail/Arrest",
            "APS Referral",
            "Hotel Voucher",
            "MCT Transport (Non M.H.)",
            "Agency/Comm Svs Supp",
            "Physical Intervention",
            "Emergency Petition",
            "Crisis Bed Referral",
            "Shelter Referral",
            "MCT to follow-up",
            "Contact EMT",
            "Family Education",
            "Assist with EP",
            "IOP Referral",
            "Crisis Plan",
            "Client refused or unavailable",
            "Diversion/Redirection",
            "Evaluation",
            "Voluntary ER Visit",
            "TCM Referral",
            "Non-mental Health Referral",
            "Contact Police",
            "Escort to Hospital",
            "Stable upon MCT arrival",
            "CPS Referral",
            "Outpatient Referral",
            "Situation Stable",
            "Verbal De-escalation",
            "Client Education",
            "Other"});
            this.Interventions.Location = new System.Drawing.Point(5, 23);
            this.Interventions.MultiColumn = true;
            this.Interventions.Name = "Interventions";
            this.Interventions.Size = new System.Drawing.Size(607, 94);
            this.Interventions.TabIndex = 43;
            // 
            // OtherDesclbl
            // 
            this.OtherDesclbl.AutoSize = true;
            this.OtherDesclbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OtherDesclbl.Location = new System.Drawing.Point(8, 131);
            this.OtherDesclbl.Name = "OtherDesclbl";
            this.OtherDesclbl.Size = new System.Drawing.Size(31, 12);
            this.OtherDesclbl.TabIndex = 40;
            this.OtherDesclbl.Text = "Other:";
            // 
            // Other
            // 
            this.Other.Location = new System.Drawing.Point(11, 147);
            this.Other.Multiline = true;
            this.Other.Name = "Other";
            this.Other.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Other.Size = new System.Drawing.Size(350, 48);
            this.Other.TabIndex = 39;
            // 
            // MCTDispatchView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.toolStrip1);
            this.Name = "MCTDispatchView";
            this.Size = new System.Drawing.Size(630, 640);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.Section1TabPage.ResumeLayout(false);
            this.Section1TabPage.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.DispatchedGroupBox.ResumeLayout(false);
            this.DispatchedGroupBox.PerformLayout();
            this.ClientInfoGroupBox.ResumeLayout(false);
            this.ClientInfoGroupBox.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Mileage)).EndInit();
            this.Section2TabPage.ResumeLayout(false);
            this.Section2TabPage.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox7.ResumeLayout(false);
            this.groupBox7.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton SaveToolStripButton;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage Section1TabPage;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TextBox Information;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TextBox OthersInvolved;
        private System.Windows.Forms.ComboBox Precinct;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.ComboBox location;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.GroupBox DispatchedGroupBox;
        private System.Windows.Forms.RadioButton dispatch_followup;
        private System.Windows.Forms.RadioButton dispatch_new;
        private System.Windows.Forms.GroupBox ClientInfoGroupBox;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox CaseNumber;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox Team;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label CaseNumberlabel;
        private System.Windows.Forms.TabPage Section2TabPage;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.TextBox Additional;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Label OtherDesclbl;
        private System.Windows.Forms.TextBox Other;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TextBox UserName;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox OtherDesc;
        private System.Windows.Forms.DateTimePicker ArrivalTime;
        private System.Windows.Forms.DateTimePicker DispatchTime;
        private System.Windows.Forms.NumericUpDown Mileage;
        private System.Windows.Forms.TextBox Time;
        private System.Windows.Forms.TextBox Date;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.TextBox Enviromental;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.GroupBox groupBox8;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.ComboBox Diagnostic;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.ComboBox DispatchedBy;
        private System.Windows.Forms.TextBox TotalTime;
        private System.Windows.Forms.DateTimePicker DispatchDate;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.DateTimePicker EndTime;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.DateTimePicker EndDate;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.DateTimePicker ArrivalDate;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.GroupBox groupBox10;
        private System.Windows.Forms.RadioButton DivertedJail_na;
        private System.Windows.Forms.RadioButton DivertedJail_no;
        private System.Windows.Forms.RadioButton DivertedJail_yes;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.RadioButton DivertedER_na;
        private System.Windows.Forms.RadioButton DivertedER_no;
        private System.Windows.Forms.RadioButton DivertedER_yes;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox OtherOutcomeDet;
        private System.Windows.Forms.CheckedListBox Interventions;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckedListBox FocalIssues;
        private System.Windows.Forms.CheckedListBox Treatment;
        private System.Windows.Forms.CheckedListBox Outcome;
        //private System.Windows.Forms.Label DivertedCall;
    }
}

