//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI.SmartParts;
using Sante.EMR.SmartClient.MCT.Services;
using Microsoft.Practices.CompositeUI.EventBroker;
using Sante.EMR.SmartClient.Infrastructure.Interface.Constants;

namespace Sante.EMR.SmartClient.IHIT
{
    public partial class TelephoneContactViewPresenter : Presenter<IIHITView>
    {
        private IWorkflowStateService _state;
        public TelephoneContactViewPresenter([ServiceDependency] IWorkflowStateService workflow)
        {
            _state = workflow;
        }

        /// <summary>
        /// This method is a placeholder that will be called by the view when it has been loaded.
        /// </summary>
        public override void OnViewReady()
        {
            base.OnViewReady();
            _state.Depart = "IHIT";
        }

        /// <summary>
        /// Close the view
        /// </summary>
        public void OnCloseView()
        {
            base.CloseView();
        }

        public ISmartPartInfo GetSmartPartInfo(Type smartPartInfoType)
        {
            ISmartPartInfo result =
            (ISmartPartInfo)Activator.CreateInstance(smartPartInfoType);
            result.Title = "IHIT Menu";//String.Format("Case List #{0}", this._caseQueue.Id);
            result.Description = "Select a IHIT form to fill out.";

            return result;

        }

        internal void ShowForm(string p)
        {
            EventArgs<string> s = new EventArgs<string>(p);
            _state.NextForm = p;
            WorkItem.EventTopics[p].Fire(this, s, WorkItem, PublicationScope.Global);
        }

        internal void ShowFormWithCaseSelection(string p)
        {
            EventArgs<string> s = new EventArgs<string>(p);
            _state.NextForm = p;
            WorkItem.EventTopics[EventTopicNames.ShowCaseNumberSelection].Fire(this, s, WorkItem, PublicationScope.Global);
        }
    }
}

