//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace Sante.EMR.SmartClient.OutBox.DataWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataServiceSoap", Namespace="http://emr.santegroup.org/")]
    public partial class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModifiedTablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOPSCasesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveMCTCasesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveIHITCasesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataService() {
            this.Url = global::Sante.EMR.SmartClient.OutBox.Properties.Settings.Default.OutBox_DataWebService_DataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetModifiedTablesCompletedEventHandler GetModifiedTablesCompleted;
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        public event GetTasksCompletedEventHandler GetTasksCompleted;
        
        /// <remarks/>
        public event GetOPSCasesCompletedEventHandler GetOPSCasesCompleted;
        
        /// <remarks/>
        public event RetrieveMCTCasesCompletedEventHandler RetrieveMCTCasesCompleted;
        
        /// <remarks/>
        public event RetrieveIHITCasesCompletedEventHandler RetrieveIHITCasesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/HelloWorld", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/GetModifiedTables", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetModifiedTables() {
            object[] results = this.Invoke("GetModifiedTables", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetModifiedTablesAsync() {
            this.GetModifiedTablesAsync(null);
        }
        
        /// <remarks/>
        public void GetModifiedTablesAsync(object userState) {
            if ((this.GetModifiedTablesOperationCompleted == null)) {
                this.GetModifiedTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModifiedTablesOperationCompleted);
            }
            this.InvokeAsync("GetModifiedTables", new object[0], this.GetModifiedTablesOperationCompleted, userState);
        }
        
        private void OnGetModifiedTablesOperationCompleted(object arg) {
            if ((this.GetModifiedTablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModifiedTablesCompleted(this, new GetModifiedTablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/Search", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Patient[] Search(string firstname, string lastname, string phone, string address, string casenumber) {
            object[] results = this.Invoke("Search", new object[] {
                        firstname,
                        lastname,
                        phone,
                        address,
                        casenumber});
            return ((Patient[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string firstname, string lastname, string phone, string address, string casenumber) {
            this.SearchAsync(firstname, lastname, phone, address, casenumber, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string firstname, string lastname, string phone, string address, string casenumber, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        firstname,
                        lastname,
                        phone,
                        address,
                        casenumber}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/GetTasks", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NextTask[] GetTasks(int casenumber) {
            object[] results = this.Invoke("GetTasks", new object[] {
                        casenumber});
            return ((NextTask[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTasksAsync(int casenumber) {
            this.GetTasksAsync(casenumber, null);
        }
        
        /// <remarks/>
        public void GetTasksAsync(int casenumber, object userState) {
            if ((this.GetTasksOperationCompleted == null)) {
                this.GetTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTasksOperationCompleted);
            }
            this.InvokeAsync("GetTasks", new object[] {
                        casenumber}, this.GetTasksOperationCompleted, userState);
        }
        
        private void OnGetTasksOperationCompleted(object arg) {
            if ((this.GetTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTasksCompleted(this, new GetTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/GetOPSCases", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Case[] GetOPSCases() {
            object[] results = this.Invoke("GetOPSCases", new object[0]);
            return ((Case[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOPSCasesAsync() {
            this.GetOPSCasesAsync(null);
        }
        
        /// <remarks/>
        public void GetOPSCasesAsync(object userState) {
            if ((this.GetOPSCasesOperationCompleted == null)) {
                this.GetOPSCasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOPSCasesOperationCompleted);
            }
            this.InvokeAsync("GetOPSCases", new object[0], this.GetOPSCasesOperationCompleted, userState);
        }
        
        private void OnGetOPSCasesOperationCompleted(object arg) {
            if ((this.GetOPSCasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOPSCasesCompleted(this, new GetOPSCasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/RetrieveMCTCases", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RetrieveMCTCases() {
            object[] results = this.Invoke("RetrieveMCTCases", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveMCTCasesAsync() {
            this.RetrieveMCTCasesAsync(null);
        }
        
        /// <remarks/>
        public void RetrieveMCTCasesAsync(object userState) {
            if ((this.RetrieveMCTCasesOperationCompleted == null)) {
                this.RetrieveMCTCasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveMCTCasesOperationCompleted);
            }
            this.InvokeAsync("RetrieveMCTCases", new object[0], this.RetrieveMCTCasesOperationCompleted, userState);
        }
        
        private void OnRetrieveMCTCasesOperationCompleted(object arg) {
            if ((this.RetrieveMCTCasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveMCTCasesCompleted(this, new RetrieveMCTCasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://emr.santegroup.org/RetrieveIHITCases", RequestNamespace="http://emr.santegroup.org/", ResponseNamespace="http://emr.santegroup.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RetrieveIHITCases() {
            object[] results = this.Invoke("RetrieveIHITCases", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveIHITCasesAsync() {
            this.RetrieveIHITCasesAsync(null);
        }
        
        /// <remarks/>
        public void RetrieveIHITCasesAsync(object userState) {
            if ((this.RetrieveIHITCasesOperationCompleted == null)) {
                this.RetrieveIHITCasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveIHITCasesOperationCompleted);
            }
            this.InvokeAsync("RetrieveIHITCases", new object[0], this.RetrieveIHITCasesOperationCompleted, userState);
        }
        
        private void OnRetrieveIHITCasesOperationCompleted(object arg) {
            if ((this.RetrieveIHITCasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveIHITCasesCompleted(this, new RetrieveIHITCasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emr.santegroup.org/")]
    public partial class Patient {
        
        private System.DateTime dOBField;
        
        private string sSNField;
        
        private string phoneField;
        
        private int zipcodeField;
        
        private string stateField;
        
        private string cityField;
        
        private string streeAddressField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private int patientIDField;
        
        private int caseNumberField;
        
        /// <remarks/>
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StreeAddress {
            get {
                return this.streeAddressField;
            }
            set {
                this.streeAddressField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public int PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
            }
        }
        
        /// <remarks/>
        public int CaseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emr.santegroup.org/")]
    public partial class Form {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emr.santegroup.org/")]
    public partial class Case {
        
        private Form[] formsField;
        
        private NextTask nextTaskObjField;
        
        private System.DateTime setDateField;
        
        private string commentsField;
        
        private string closedInitialsField;
        
        private System.DateTime statusDateField;
        
        private System.DateTime tstampField;
        
        private string openByField;
        
        private System.DateTime nextTaskDateField;
        
        private Status statusField;
        
        private System.DateTime dateClosedField;
        
        private string nextTaskField;
        
        private System.DateTime dateOpenedField;
        
        private int caseNumberField;
        
        /// <remarks/>
        public Form[] Forms {
            get {
                return this.formsField;
            }
            set {
                this.formsField = value;
            }
        }
        
        /// <remarks/>
        public NextTask NextTaskObj {
            get {
                return this.nextTaskObjField;
            }
            set {
                this.nextTaskObjField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SetDate {
            get {
                return this.setDateField;
            }
            set {
                this.setDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string ClosedInitials {
            get {
                return this.closedInitialsField;
            }
            set {
                this.closedInitialsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StatusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Tstamp {
            get {
                return this.tstampField;
            }
            set {
                this.tstampField = value;
            }
        }
        
        /// <remarks/>
        public string OpenBy {
            get {
                return this.openByField;
            }
            set {
                this.openByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NextTaskDate {
            get {
                return this.nextTaskDateField;
            }
            set {
                this.nextTaskDateField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateClosed {
            get {
                return this.dateClosedField;
            }
            set {
                this.dateClosedField = value;
            }
        }
        
        /// <remarks/>
        public string NextTask {
            get {
                return this.nextTaskField;
            }
            set {
                this.nextTaskField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOpened {
            get {
                return this.dateOpenedField;
            }
            set {
                this.dateOpenedField = value;
            }
        }
        
        /// <remarks/>
        public int CaseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emr.santegroup.org/")]
    public partial class NextTask {
        
        private string apptField;
        
        private string nameField;
        
        private string statusField;
        
        private System.DateTime dateCompletedField;
        
        private string initialField;
        
        private System.DateTime dateDueField;
        
        private System.DateTime setDateField;
        
        private string commentsField;
        
        /// <remarks/>
        public string Appt {
            get {
                return this.apptField;
            }
            set {
                this.apptField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCompleted {
            get {
                return this.dateCompletedField;
            }
            set {
                this.dateCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string Initial {
            get {
                return this.initialField;
            }
            set {
                this.initialField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateDue {
            get {
                return this.dateDueField;
            }
            set {
                this.dateDueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SetDate {
            get {
                return this.setDateField;
            }
            set {
                this.setDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emr.santegroup.org/")]
    public enum Status {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Unresolved,
        
        /// <remarks/>
        FollowUp,
        
        /// <remarks/>
        FrequentCaller,
        
        /// <remarks/>
        MCT,
        
        /// <remarks/>
        EastIHIT,
        
        /// <remarks/>
        WestIHIT,
        
        /// <remarks/>
        CISM,
        
        /// <remarks/>
        Closure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetModifiedTablesCompletedEventHandler(object sender, GetModifiedTablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModifiedTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModifiedTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Patient[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Patient[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetTasksCompletedEventHandler(object sender, GetTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NextTask[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NextTask[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetOPSCasesCompletedEventHandler(object sender, GetOPSCasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOPSCasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOPSCasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Case[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Case[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RetrieveMCTCasesCompletedEventHandler(object sender, RetrieveMCTCasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveMCTCasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveMCTCasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RetrieveIHITCasesCompletedEventHandler(object sender, RetrieveIHITCasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveIHITCasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveIHITCasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591