//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// This class contains placeholder methods for the common module initialization 
// tasks, such as adding services, or user-interface element
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using Sante.EMR.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.Commands;
using Sante.EMR.SmartClient.OutBox.Constants;
//using Sante.EMR.SmartClient.OutBox.DSA.DataService;
using Sante.EMR.SmartClient.OutBox.Services;

namespace Sante.EMR.SmartClient.OutBox
{
    public class ModuleController : WorkItemController
    {
        public override void Run()
        {
            AddServices();
            ExtendMenu();
            ExtendToolStrip();
            AddViews();
        }

        private void AddServices()
        {
            //TODO: add services provided by the Module. See: Add or AddNew method in 
            //		WorkItem.Services collection or see ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.2005Nov.cab/CAB/html/03-020-Adding%20Services.htm
            //WorkItem.Services.AddNew<Agent>();
            //WorkItem.Services.AddNew<IFormHandlerService>();
        }

        private void ExtendMenu()
        {
            ToolStripMenuItem menu = new ToolStripMenuItem(Properties.Resources.ModuleTitle);

            WorkItem.UIExtensionSites[UIExtensionSiteNames.FileMenu].Add(menu);
        
        }

        private void ExtendToolStrip()
        {
            //TODO: add new items to the ToolStrip in the Shell. See the UIExtensionSites collection in the WorkItem. 
            //		See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-04-340-Showing_UIElements.htm
            this.RegisterLaunchPoint(Properties.Resources.ModuleTitle, Properties.Resources.OutboxIcon, CommandNames.ShowOutbox);
        }

        private void AddViews()
        {
            //TODO: create the Module views, add them to the WorkItem and show them in 
            //		a Workspace. See: ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-040-How_to_Add_a_View_with_a_Presenter.htm

            // To create and add a view you can customize the following sentence
            // SampleView view = ShowViewInWorkspace<SampleView>(WorkspaceNames.SampleWorkspace);

        }
        [CommandHandler(CommandNames.ShowOutbox)]
        public void OnShowOutbox(object sender, EventArgs e)
        {
            ShowViewInWorkspace<OutBoxView>(WorkspaceNames.PrimaryWorkspace);
        }
    }
}
